Repository direktiv/direktiv, pull requests merged in 2022-07, with the labels that each got.

#607 Updated cloudevents dependency. This seems to fix some bugs that aros…
  go.mod
  go.sum
Labels: bug

#608 CLI Enhancements & Fixes
  cmd/exec/main.go
  cmd/exec/operations.go
Labels: enhancement, cli

#610 Minor refactor of event logic to better handle errors.
  pkg/flow/events.go
Labels: bug

#613 Increase SSE Heartbeat Frequency
  pkg/api/util.go
Labels: bug

#639 Closes #629
  pkg/model/common-structures.go
  pkg/model/state-events-and.go
  pkg/model/state-events-xor.go
Labels: bug

#640 Fixes #633.
  pkg/flow/states/foreach.go
Labels: bug

#641 Makes FunctionFiles fully jq-able.
  pkg/flow/states/action-helpers.go
  pkg/flow/states/action.go
  pkg/flow/states/foreach.go
  pkg/flow/states/helpers.go
  pkg/flow/states/parallel.go
  pkg/model/function-common.go
Labels: enhancement

#642 Fixes #611
  pkg/flow/syncer.go
Labels: bug

#644 Removes the ability to scale knative-workflow functions.
  pkg/flow/temporary.go
  pkg/functions/kube.go
  pkg/functions/server.go
  pkg/model/function-global.go
  pkg/model/function-namespaced.go
  pkg/model/function-reusable.go
Labels: enhancement
