Repository direktiv/direktiv, pull requests merged in 2022-05, with the labels that each got.

#524 Improves usability of cloudevents by ensuring something makes it thro…
  pkg/api/flow.go
Labels: enhancement

#527 Getter and setter states 'key' fields are now evaluated as JQ, as is …
  pkg/flow/dependency-graph.go
  pkg/flow/errors.go
  pkg/flow/state-getter.go
  pkg/flow/state-setter.go
  pkg/model/state-getter.go
  pkg/model/state-setter.go
  pkg/model/workflow.go
  specification/workflow-yaml/getter.md
  specification/workflow-yaml/setter.md
Labels: documentation, enhancement

#546 Fixes #543.
  pkg/flow/state-setter.go
Labels: bug

#544 Mirror cron bugfix.
  pkg/flow/syncer.go
Labels: bug

#553 Enforces mirror locks better, including for crons.
  pkg/flow/syncer.go
Labels: bug

#561 Fixes an inconsistency between a streaming and a non-streaming API.
  pkg/flow/grpc-mirror.go
Labels: bug

#564 Fixes #557
  pkg/flow/grpc-workflow.go
  pkg/flow/routing.go
  pkg/flow/syncer.go
Labels: bug

#571 Fixes two minor bugs in the mirror syncing logic.
  pkg/flow/syncer.go
Labels: bug

#584 Fixes #575
  pkg/flow/actions.go
  pkg/flow/cancel.go
  pkg/flow/locks.go
Labels: bug

#585 Bug 575
  pkg/functions/kube.go
  pkg/functions/lock.go
  specification/workflow-yaml/action.md
Labels: bug
