Repository direktiv/direktiv, pull requests merged in 2022-10, with the labels that each got.

#679 Automatic support for proxying in libgit2 logic.
  pkg/flow/syncer.go
Labels: bug

#691 Puts all user-facing logs into a queue so that main-logic can continu…
  pkg/flow/logs.go
  pkg/flow/server.go
Labels: enhancement

#696 change error message to direktiv-sync
  cmd/exec/main.go
Labels: bug, cli
