Repository direktiv/direktiv, pull requests merged in 2022-11, with the labels that each got.

#682 Add folder functionality and update to secrets v1
  pkg/api/flow.go
  pkg/api/routes.go
  pkg/flow/grpc-secrets.go
  pkg/flow/grpc/build.pb.go
  pkg/flow/grpc/cloudevent.pb.go
  pkg/flow/grpc/eventing.pb.go
  pkg/flow/grpc/instances.pb.go
  pkg/flow/grpc/internal.pb.go
  pkg/flow/grpc/logs.pb.go
  pkg/flow/grpc/mirror.pb.go
  pkg/flow/grpc/namespaces.pb.go
  pkg/flow/grpc/nodes.pb.go
  pkg/flow/grpc/pagination.pb.go
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
  pkg/flow/grpc/registries.pb.go
  pkg/flow/grpc/secrets.pb.go
  pkg/flow/grpc/secrets.proto
  pkg/flow/grpc/util.pb.go
  pkg/flow/grpc/variables.pb.go
  pkg/flow/grpc/workflows.pb.go
  pkg/flow/secrets.go
  pkg/functions/grpc/build.pb.go
  pkg/functions/grpc/cancel-workflow.pb.go
  pkg/functions/grpc/functions-common.pb.go
  pkg/functions/grpc/functions-create.pb.go
  pkg/functions/grpc/functions-get.pb.go
  pkg/functions/grpc/functions-list.pb.go
  pkg/functions/grpc/functions-reconstruct.pb.go
  pkg/functions/grpc/functions-traffic.pb.go
  pkg/functions/grpc/functions-update.pb.go
  pkg/functions/grpc/pod-list.pb.go
  pkg/functions/grpc/protocol.pb.go
  pkg/functions/grpc/protocol_grpc.pb.go
  pkg/functions/grpc/registries-get.pb.go
  pkg/functions/grpc/registries-global.pb.go
  pkg/functions/grpc/registry-delete.pb.go
  pkg/functions/grpc/registry-store.pb.go
  pkg/functions/grpc/revision-delete.pb.go
  pkg/functions/grpc/watch-functions.pb.go
  pkg/functions/grpc/watch-logs.pb.go
  pkg/functions/grpc/watch-pods.pb.go
  pkg/functions/grpc/watch-revisions.pb.go
  pkg/health/proto.pb.go
  pkg/health/proto_grpc.pb.go
  pkg/secrets/grpc/protocol.pb.go
  pkg/secrets/grpc/protocol.proto
  pkg/secrets/grpc/protocol_grpc.pb.go
  pkg/secrets/grpc/secrets.pb.go
  pkg/secrets/grpc/secrets.proto
  pkg/secrets/handler/db.go
  pkg/secrets/handler/handlers.go
  pkg/secrets/server.go
  pkg/secrets/server_test.go
  pkg/util/regex.go
  scripts/.dev.yaml.swp
  scripts/api/api.md
  scripts/api/swagger.json
  scripts/dev.yaml
Labels: enhancement

#695 trigger event from cli
  cmd/exec/main.go
  cmd/exec/operations.go
Labels: enhancement, cli

#709 protoc and ent build container
  Makefile
  build/ent/Dockerfile
  build/ent/run.sh
  build/protoc/Dockerfile
Labels: enhancement

#699 given empty var value in setter will delete var
  pkg/flow/grpc-workflow-variables.go
  pkg/flow/temporary.go
Labels: enhancement

#718 allow retrigger events which id field includes slashes
  pkg/api/flow.go
Labels: enhancement

#704 Filter broadcast events
  .gitignore
  pkg/api/flow.go
  pkg/api/routes.go
  pkg/flow/ent/client.go
  pkg/flow/ent/cloudeventfilters.go
  pkg/flow/ent/cloudeventfilters/cloudeventfilters.go
  pkg/flow/ent/cloudeventfilters/where.go
  pkg/flow/ent/cloudeventfilters_create.go
  pkg/flow/ent/cloudeventfilters_delete.go
  pkg/flow/ent/cloudeventfilters_query.go
  pkg/flow/ent/cloudeventfilters_update.go
  pkg/flow/ent/config.go
  pkg/flow/ent/ent.go
  pkg/flow/ent/hook/hook.go
  pkg/flow/ent/migrate/schema.go
  pkg/flow/ent/mutation.go
  pkg/flow/ent/namespace.go
  pkg/flow/ent/namespace/namespace.go
  pkg/flow/ent/namespace/where.go
  pkg/flow/ent/namespace_create.go
  pkg/flow/ent/namespace_query.go
  pkg/flow/ent/namespace_update.go
  pkg/flow/ent/predicate/predicate.go
  pkg/flow/ent/runtime.go
  pkg/flow/ent/schema/cloudeventfilters.go
  pkg/flow/ent/schema/namespace.go
  pkg/flow/ent/tx.go
  pkg/flow/eventfilter_test.go
  pkg/flow/events.go
  pkg/flow/grpc/cloudevent.pb.go
  pkg/flow/grpc/cloudevent.proto
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
  pkg/metrics/ent/config.go
  pkg/metrics/ent/metrics_create.go
  pkg/metrics/ent/metrics_query.go
  pkg/metrics/ent/metrics_update.go
  pkg/metrics/ent/tx.go
  pkg/secrets/ent/config.go
  pkg/secrets/ent/namespacesecret_create.go
  pkg/secrets/ent/namespacesecret_query.go
  pkg/secrets/ent/namespacesecret_update.go
  pkg/secrets/ent/tx.go
Labels: enhancement

#725 Reverts one small change that broke mirrors.
  pkg/flow/syncer.go
Labels: bug
