Repository direktiv/direktiv, pull requests merged in 2024-05, with the labels that each got.

#1515 [DIR-1508] Tweaks the instance apis.
  openapi/src/paths/instances.yaml
  pkg/refactor/api/instances.go
  tests/instances/blobs.test.js
  tests/instances/wait-success.test.js
Labels: improvement, backend

#1516 [DIR-1521] Tweaks notifications api.
  openapi/src/paths/notifications.yaml
  pkg/refactor/api/notifications.go
  tests/part1/notifications/uninitialized_secrets.test.js
Labels: improvement, backend

#1517 [DIR-1488] Removes the outdated metrics table from the database.
  pkg/refactor/database/db_schema.sql
Labels: backend, refactor

#1520 [DIR-1528] implement gateway2 mvp module
  .golangci.yaml
  pkg/refactor/api/api.go
  pkg/refactor/cmd/main.go
  pkg/refactor/core/app.go
  pkg/refactor/core/gateway2.go
  pkg/refactor/gateway2/gateway.go
  pkg/refactor/gateway2/plugins/basic_auth.go
  pkg/refactor/gateway2/plugins/plugins.go
Labels: feature, backend

#1494 [DIR-1502] update UI to get notifications from v2 api
  ui/src/api/namespaceLinting/index.ts
  ui/src/api/namespaceLinting/schema.ts
  ui/src/api/notifications/index.ts
  ui/src/api/notifications/query/get.ts
  ui/src/api/notifications/schema.ts
  ui/src/components/NotificationMenu/NotificationItem.tsx
  ui/src/components/NotificationMenu/config.ts
  ui/src/components/NotificationMenu/index.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Workflow/index.tsx
  ui/src/pages/namespace/Explorer/Workflow/Edit/WorkflowEditor.tsx
  ui/src/pages/namespace/Settings/Secrets/index.tsx
Labels: ui

#1522 Minor issues fixes
  pkg/flow/grpc/protocol.proto
  pkg/health/proto.pb.go
  pkg/health/proto.proto
  pkg/health/proto_grpc.pb.go
  tests/events/events_v2.test.js
Labels: bug, backend

#1527 [DIR-1533] fix api/v2/namespace isSystemNamespace field
  pkg/refactor/api/namespaces.go
  tests/part2/namespaces/basic_create.test.js
Labels: bug, backend

#1497 [DIR-1444] [DIR-724] [DIR-1506] migrate to new instances api
  ui/e2e/explorer/consumer/index.spec.ts
  ui/e2e/explorer/workflow/run.spec.ts
  ui/e2e/explorer/workflow/settings.spec.ts
  ui/e2e/instances/details/index.spec.ts
  ui/e2e/instances/filter/index.spec.ts
  ui/e2e/instances/list/index.spec.ts
  ui/e2e/instances/utils/index.ts
  ui/public/locales/en/translation.json
  ui/src/api/__tests__/utils.test.ts
  ui/src/api/files/__tests__/schema.test.ts
  ui/src/api/files/schema.ts
  ui/src/api/instances/index.ts
  ui/src/api/instances/mutate/cancel.ts
  ui/src/api/instances/mutate/create.ts
  ui/src/api/instances/query/__tests__/get.ts
  ui/src/api/instances/query/details.ts
  ui/src/api/instances/query/details/index.ts
  ui/src/api/instances/query/details/streaming.ts
  ui/src/api/instances/query/get.ts
  ui/src/api/instances/query/input.ts
  ui/src/api/instances/query/output.ts
  ui/src/api/instances/query/utils.ts
  ui/src/api/instances/schema.ts
  ui/src/api/tree/index.ts
  ui/src/api/tree/schema/node.ts
  ui/src/api/utils.ts
  ui/src/api/variables/index.ts
  ui/src/components/NamespaceEdit/index.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Directory.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Gateway/Consumer.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Gateway/Route.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Service/index.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Workflow/index.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/Rename.tsx
  ui/src/pages/namespace/Explorer/Workflow/ApiCommands/index.tsx
  ui/src/pages/namespace/Explorer/Workflow/ApiCommands/utils.ts
  ui/src/pages/namespace/Explorer/Workflow/Overview/Instances.tsx
  ui/src/pages/namespace/Explorer/Workflow/components/RunWorkflow.tsx
  ui/src/pages/namespace/Instances/Detail/Header/ChildInstances.tsx
  ui/src/pages/namespace/Instances/Detail/Header/index.tsx
  ui/src/pages/namespace/Instances/Detail/InstanceDetail.tsx
  ui/src/pages/namespace/Instances/Detail/Main/Diagram/index.tsx
  ui/src/pages/namespace/Instances/Detail/Main/InputOutput/Input.tsx
  ui/src/pages/namespace/Instances/Detail/Main/InputOutput/Output.tsx
  ui/src/pages/namespace/Instances/Detail/Main/InputOutput/index.tsx
  ui/src/pages/namespace/Instances/Detail/Main/Logs/ScrollContainer.tsx
  ui/src/pages/namespace/Instances/Detail/Main/Logs/index.tsx
  ui/src/pages/namespace/Instances/Detail/index.tsx
  ui/src/pages/namespace/Instances/List/Row.tsx
  ui/src/pages/namespace/Instances/List/index.tsx
  ui/src/pages/namespace/Instances/components/Filters/Options.tsx
  ui/src/pages/namespace/Instances/components/Filters/index.tsx
  ui/src/pages/namespace/Monitoring/Instances/Row.tsx
  ui/src/pages/namespace/Monitoring/Instances/index.tsx
Labels: ui, refactor

#1529 Cleanup e2e test data
  ui/e2e/mirror.spec.ts
Labels: ui, testing

#1518 [DIR-1448] Adds jx api.
  openapi/src/paths/jx.yaml
  pkg/jqer/jqer.go
  pkg/refactor/api/api.go
  pkg/refactor/api/jx.go
  tests/package-lock.json
  tests/package.json
  tests/part1/api/jx.test.js
  tests/yarn.lock
Labels: backend, refactor

#1530 [DIR-1466] Fixes a bug in the synchronization logic of the engine.
  pkg/flow/memory.go
  pkg/flow/scheduling.go
  pkg/refactor/instancestore/instancestoresql/instance_data_query.go
  tests/engine/sync.test.js
Labels: bug, backend

#1505 [DIR-1493] Add E2E Tests for the Instance Page - Logs
  ui/e2e/instances/details/diagram.ts
  ui/e2e/instances/details/header.ts
  ui/e2e/instances/details/index.spec.ts
  ui/e2e/instances/details/inputOutput.ts
  ui/e2e/instances/details/logs.ts
  ui/e2e/instances/utils/workflows.ts
  ui/src/pages/namespace/Instances/Detail/Main/Logs/ScrollContainer.tsx
  ui/src/pages/namespace/Instances/Detail/Main/Logs/index.tsx
  ui/src/pages/namespace/Instances/Detail/Main/index.tsx
Labels: ui, testing

#1526 [DIR-1519] target plugins should only allow namespace selection from the system namespace
  ui/public/locales/en/translation.json
  ui/src/api/namespaces/schema/namespace.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/TargetEventForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/TargetFlowForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/TargetFlowVarForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/TargetNamespaceFileForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/TargetNamespaceVarForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/utils/DisableNamespaceSelectNote.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/utils/useIsSystemNamespace.ts
Labels: improvement, ui

#1532 [DIR-1532] bug when using eventsxor to route between same type with attributes
  pkg/flow/db-events.go
  pkg/flow/routing.go
  pkg/flow/server.go
  pkg/refactor/api/events.go
  pkg/refactor/cmd/main.go
  pkg/refactor/database/db_schema.sql
  pkg/refactor/datastore/datastoresql/eventstore_listener.go
  pkg/refactor/datastore/datastoresql/eventstore_listener_test.go
  pkg/refactor/datastore/datastoresql/eventstore_topic.go
  pkg/refactor/datastore/eventsstore.go
  pkg/refactor/events/glob_test.go
  pkg/refactor/events/process.go
  pkg/refactor/events/process_test.go
Labels: bug, backend

#1535 [DIR-1541] implement basic auth e2e test
  pkg/refactor/gateway2/gateway.go
  tests/gateway/endpoints_crud.test.js
  tests/gateway2/basic_auth.test.js
Labels: backend, refactor

#1537 House Keeping
  .github/workflows/build.yml
  .golangci.yaml
  cmd/sidecar/local-server.go
  cmd/sidecar/worker.go
  make_tests.mk
  pkg/api/flow.go
  pkg/api/server.go
  pkg/flow/instance_messages.go
  pkg/refactor/api/events.go
  pkg/refactor/api/plattformlogs.go
  pkg/refactor/gateway/plugins/auth/slack-event.go
  pkg/util/telemetry.go
  tests/engine/sync.test.js
  tests/gateway2/basic.test.js
  tests/gateway2/basic_auth.test.js
  tests/part1/api/jx.test.js
Labels: backend, refactor

#1538 House Keeping
  tests/gateway/endpoints_crud.test.js
Labels: bug

#1539 [DIR-1497] Adds e2e tests for current system services functionality.
  tests/services/system_services.test.js
Labels: backend, devops

#1540 [DIR-1542] - change endpoint that is used for checkApiKeyAgainstServer
  ui/src/api/authenticate/index.ts
Labels: bug, ui

#1544 [DIR-1545] Updated charts for additional envs
  charts/direktiv/templates/flow/flow-deployment.yaml
  charts/direktiv/templates/frontend/frontend-deployment.yaml
  make_direktiv_ui.mk
  ui/conf/entrypoint.sh
  ui/conf/nginx.conf
Labels: charts

#1542 [DIR-1544] Fix rendering loop is returning to early
  pkg/flow/db-events.go
Labels: bug, backend

#1543 House Keeping
  tests/events/workflow_events_or.test.js
  tests/services/system_services.test.js
Labels: bug

#1546 House Keeping
  .github/workflows/build.yml
  pkg/refactor/cmd/main.go
  tests/events/workflow_events_or.test.js
Labels: bug

#1547 House Keeping
  .github/workflows/build.yml
Labels: backend

#1549 House Keeping
  .github/workflows/build.yml
Labels: backend

#1550 [DIR-1553] Bugfixes
  pkg/flow/errors.go
  pkg/flow/jq.go
  pkg/flow/states/helpers.go
  pkg/flow/states/setter.go
  pkg/jqer/jqer.go
  pkg/refactor/api/instances.go
  pkg/refactor/api/jx.go
  tests/engine/simple-events.test.js
  tests/part1/api/jx.test.js
Labels: bug, backend

#1551 House Keeping
  tests/events/workflow_events_and.test.js
Labels: bug, backend

#1552 [DIR-1554} UI make target fixed
  make_direktiv_ui.mk
Labels: devops

#1554 [DIR-1556] Fix db migration line
  pkg/refactor/database/db_schema.sql
Labels: bug, backend

#1556 [DIR-1557] gateway2: implement fetchSecret() magic function in consumer file
  pkg/refactor/cmd/main.go
  pkg/refactor/core/gateway2.go
  pkg/refactor/gateway2/fetch_secret.go
  pkg/refactor/gateway2/fetch_secret_test.go
  pkg/refactor/gateway2/gateway.go
  tests/gateway2/fetch_secret.test.js
Labels: backend

#1557 [DIR-1557] gateway2 implement lock free wait free feature
  cmd/direktiv/main.go
  pkg/refactor/gateway2/gateway.go
  pkg/refactor/gateway2/helper.go
  pkg/refactor/gateway2/plugins/auth/basic_auth.go
  pkg/refactor/gateway2/plugins/plugins.go
  pkg/refactor/gateway2/plugins/target/debug_target.go
  pkg/refactor/gateway2/router.go
Labels: backend, refactor

#1558 House Keeping
  pkg/refactor/gateway2/plugins/auth/basic_auth.go
  pkg/refactor/gateway2/plugins/target/debug_target.go
Labels: backend, refactor

#1559 [DIR-1570] Update chart version
  charts/direktiv/Chart.yaml
Labels: charts

#1511 [DIR-1509] Remove console logs from flow
  charts/direktiv/README.md
  charts/direktiv/templates/flow/flow-deployment.yaml
  charts/direktiv/templates/functions/functions-cm-config.yaml
  charts/direktiv/values.yaml
  pkg/refactor/cmd/main.go
  pkg/refactor/core/app.go
  pkg/refactor/service/helper.go
  pkg/util/env.go
Labels: configuration, backend

#1561 House Keeping
  pkg/refactor/gateway2/fetch_secret.go
  pkg/refactor/gateway2/fetch_secret_test.go
  tests/gateway2/fetch_secret.test.js
Labels: bug, backend

#1564 [DIR-1560] gateway2 migrate all inbound plugins from gateway1
  cmd/direktiv/main.go
  pkg/refactor/core/gateway2.go
  pkg/refactor/gateway2/plugins/auth/basic-auth.go
  pkg/refactor/gateway2/plugins/auth/github-event.go
  pkg/refactor/gateway2/plugins/auth/gitlab-event.go
  pkg/refactor/gateway2/plugins/auth/key-auth.go
  pkg/refactor/gateway2/plugins/auth/slack-event.go
  pkg/refactor/gateway2/plugins/inbound/acl-plugin.go
  pkg/refactor/gateway2/plugins/inbound/header_manipulation.go
  pkg/refactor/gateway2/plugins/inbound/js-inbound.go
  pkg/refactor/gateway2/plugins/inbound/request-convert.go
  pkg/refactor/gateway2/plugins/outbound/js.go
  pkg/refactor/gateway2/plugins/plugins.go
  pkg/refactor/gateway2/plugins/target/debug_target.go
  pkg/refactor/gateway2/plugins/target/instant-response.go
  pkg/refactor/gateway2/router.go
Labels: backend, refactor

#1565 House Keeping
  .golangci.yaml
  cmd/direktiv/main.go
  pkg/refactor/core/gateway2.go
  pkg/refactor/gateway2/context.go
  pkg/refactor/gateway2/gateway.go
  pkg/refactor/gateway2/helper.go
  pkg/refactor/gateway2/plugins.go
  pkg/refactor/gateway2/plugins/auth/basic-auth.go
  pkg/refactor/gateway2/plugins/auth/github-event.go
  pkg/refactor/gateway2/plugins/auth/gitlab-event.go
  pkg/refactor/gateway2/plugins/auth/key-auth.go
  pkg/refactor/gateway2/plugins/auth/slack-event.go
  pkg/refactor/gateway2/plugins/inbound/acl-plugin.go
  pkg/refactor/gateway2/plugins/inbound/header_manipulation.go
  pkg/refactor/gateway2/plugins/inbound/js-inbound.go
  pkg/refactor/gateway2/plugins/inbound/request-convert.go
  pkg/refactor/gateway2/plugins/outbound/js.go
  pkg/refactor/gateway2/plugins/target/debug_target.go
  pkg/refactor/gateway2/plugins/target/instant-response.go
  pkg/refactor/gateway2/router.go
Labels: backend, refactor

#1523 [DIR-1531] Add new encoding to sidecar
  cmd/sidecar/worker.go
  pkg/flow/isolate.go
  pkg/flow/temporary.go
  pkg/refactor/engine/action.go
Labels: backend, refactor

#1563 [DIR-1549] Migrate cli and tests to instances v2 API.
  cmd/exec/cmd/instance.go
  cmd/exec/cmd/workflows/workflows.go
  pkg/flow/grpc-instances.go
  pkg/refactor/gateway/plugins/target/target-workflow.go
  tests/engine/base64js.test.js
  tests/engine/cancel.test.js
  tests/engine/catch.test.js
  tests/engine/error-state.test.js
  tests/engine/getter-setter.test.js
  tests/engine/instance-data.test.js
  tests/engine/noop.test.js
  tests/engine/simple-chain.test.js
  tests/engine/simple-events.test.js
  tests/engine/simple-loop.test.js
  tests/engine/simple-subflow.test.js
  tests/engine/sync.test.js
  tests/events/send_helper.js
  tests/events/workflow_events.test.js
  tests/events/workflow_events_and.test.js
  tests/events/workflow_events_complex.test.js
  tests/events/workflow_events_or.test.js
  tests/kubernetes/function-patch.test.js
  tests/kubernetes/generic-container.test.js
  tests/kubernetes/special-command.test.js
  tests/part1/logparser/callpath.test.js
  tests/part1/logs/basic_namespace_logs.test.js
  tests/part1/secrets/secrets_read.test.js
  tests/services/action_workflow_and_run.test.js
  tests/services/files.test.js
  tests/services/system_services.test.js
Labels: refactor

#1568 [DIR-1577] remove instances grpc and rest apiv1 endpoints
  pkg/api/flow.go
  pkg/flow/bytedata/data.go
  pkg/flow/grpc-instances.go
  pkg/flow/grpc/instances.pb.go
  pkg/flow/grpc/instances.proto
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
Labels: backend

#1560 [DIR-1426] Update events and listeners to v2 api
  openapi/src/paths/events.yaml
  openapi/src/paths/paths.yaml
  pkg/flow/db-events.go
  pkg/flow/events.go
  pkg/refactor/api/api.go
  pkg/refactor/api/errors.go
  pkg/refactor/api/events.go
  pkg/refactor/datastore/datastoresql/eventstore_history.go
  pkg/refactor/datastore/datastoresql/eventstore_history_test.go
  pkg/refactor/datastore/datastoresql/eventstore_listener.go
  pkg/refactor/datastore/datastoresql/eventstore_listener_test.go
  pkg/refactor/datastore/datastoresql/staggingevents.go
  pkg/refactor/datastore/eventsstore.go
  pkg/refactor/events/eventworker.go
  pkg/refactor/events/process.go
  pkg/refactor/events/process_test.go
  tests/events/events_v2.test.js
  ui/e2e/events/history.spec.ts
  ui/e2e/events/listeners.spec.ts
  ui/e2e/utils/events.ts
  ui/public/locales/en/translation.json
  ui/src/api/eventListeners/query/get.ts
  ui/src/api/eventListeners/schema.ts
  ui/src/api/events/index.ts
  ui/src/api/events/mutate/replayEvent.ts
  ui/src/api/events/mutate/sendEvent.ts
  ui/src/api/events/query/EventStreamingSubscriber.tsx
  ui/src/api/events/query/__tests__/get.test.ts
  ui/src/api/events/query/get.ts
  ui/src/api/events/query/stream.ts
  ui/src/api/events/schema.ts
  ui/src/api/events/schema/filters.ts
  ui/src/api/events/schema/index.ts
  ui/src/api/utils.ts
  ui/src/components/Filters/DatePicker.tsx
  ui/src/components/Filters/RefineTime.tsx
  ui/src/pages/namespace/Events/History/EventsList.tsx
  ui/src/pages/namespace/Events/History/Row.tsx
  ui/src/pages/namespace/Events/History/Table.tsx
  ui/src/pages/namespace/Events/History/ViewEvent.tsx
  ui/src/pages/namespace/Events/History/components/Filters/index.tsx
  ui/src/pages/namespace/Events/History/index.tsx
  ui/src/pages/namespace/Events/Listeners/ListenersList.tsx
  ui/src/pages/namespace/Events/Listeners/Row.tsx
  ui/src/pages/namespace/Events/Listeners/Table.tsx
  ui/src/pages/namespace/Events/Listeners/index.tsx
  ui/src/pages/namespace/Instances/components/Filters/index.tsx
Labels: ui

#1569 House Keeping
  .github/workflows/build.yml
Labels: backend, refactor

#1571 House Keeping
  .github/workflows/build.yml
  Dockerfile
  ui/.dockerignore
  ui/Dockerfile
Labels: bug, backend

#1576 House Keeping
  .github/workflows/build.yml
Labels: bug, backend

#1577 House Keeping
  .github/workflows/build.yml
  charts/direktiv/templates/frontend/frontend-deployment.yaml
  charts/direktiv/values.yaml
Labels: backend

#1566 [DIR-1424] Render context filters in event listeners table
  ui/e2e/events/listeners.spec.ts
  ui/e2e/events/utils.ts
  ui/public/locales/en/translation.json
  ui/src/api/eventListeners/schema.ts
  ui/src/pages/namespace/Events/Listeners/ContextFilters/FilterEntry.tsx
  ui/src/pages/namespace/Events/Listeners/ContextFilters/index.tsx
  ui/src/pages/namespace/Events/Listeners/Row.tsx
  ui/src/pages/namespace/Events/Listeners/Table.tsx
Labels: improvement, ui

#1541 [DIR-1535] migrate jq Playground to V2 API
  ui/e2e/jqplayground/index.spec.ts
  ui/e2e/jqplayground/utils.ts
  ui/public/locales/en/translation.json
  ui/src/api/jq/mutate/executeQuery.ts
  ui/src/api/jq/schema.ts
  ui/src/pages/namespace/JqPlayground/Examples/exampleSnippets.ts
  ui/src/pages/namespace/JqPlayground/Examples/index.tsx
  ui/src/pages/namespace/JqPlayground/index.tsx
  ui/src/util/store/jqPlayground.ts
  ui/src/util/store/jqPlaygrpund.ts
Labels: ui, refactor

#1582 [DIR-1581] EE plugins are not selectable
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Auth/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Inbound/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Outbound/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/plugins/auth/index.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/plugins/inbound/index.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/plugins/outbound/index.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/plugins/target/index.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/plugins/utils.ts
Labels: bug, ui

#1587 [DIR-1584] Fix regex issue & missing log prints
  charts/direktiv/values.yaml
  pkg/flow/engine.go
  pkg/flow/instance_messages.go
  pkg/flow/memory.go
  pkg/flow/status.go
  pkg/refactor/api/plattformlogs.go
  pkg/refactor/datastore/namespaces.go
  pkg/refactor/engine/telemetry.go
Labels: bug, backend

#1588 [DIR-1588] remove jq v1 api
  charts/direktiv/templates/eventing.yaml
  charts/direktiv/templates/flow/flow-deployment.yaml
  charts/direktiv/templates/flow/flow-service.yaml
  charts/direktiv/values.yaml
  pkg/api/flow.go
  pkg/api/util.go
  pkg/flow/events.go
  pkg/flow/grpc-flow.go
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
  pkg/flow/grpc/util.pb.go
  pkg/flow/grpc/util.proto
  pkg/flow/server.go
  pkg/refactor/core/app.go
Labels: backend, refactor

#1589 [DIR-1279] Make path column bigger
  ui/src/pages/namespace/Gateway/Routes/Table/index.tsx
Labels: improvement, ui

#1590 [DIR-1586] Instance list shows "unknown date" in the finished at column, when an instance is still running
  ui/e2e/instances/list/index.spec.ts
  ui/src/assets/locales/en/translation.json
  ui/src/hooks/useUpdatedAt.ts
  ui/src/pages/namespace/Instances/List/Row.tsx
Labels: bug, ui

#1591 merge Cycle5-1 into main
  pkg/flow/engine.go
  pkg/flow/events.go
  pkg/flow/server.go
Labels: bug, ui, backend

#1596 [DIR-1293] update schema to allow workflow state to be null
  ui/src/api/logs/schema.ts
  ui/src/components/Logs/utils.ts
Labels: bug, ui

#1593 [DIR-1592] jq Playground: store query and input after clicking an example
  ui/e2e/jqplayground/index.spec.ts
  ui/src/pages/namespace/JqPlayground/index.tsx
Labels: bug, ui

#1598 House Keeping: fix github actions to prevent run when building step is failed
  .github/workflows/build.yml
  pkg/api/entry.go
Labels: bug, devops

#1600 House Keeping: prevent multiple concerent workflow for the same branch
  .github/workflows/build.yml
Labels: bug, devops

#1604 [DIR-1561] gateway2 migrate all target plugins from gateway1
  pkg/refactor/gateway2/context.go
  pkg/refactor/gateway2/plugins.go
  pkg/refactor/gateway2/plugins/target/request.go
  pkg/refactor/gateway2/plugins/target/target-ns-file.go
  pkg/refactor/gateway2/plugins/target/target-ns-var.go
  pkg/refactor/gateway2/plugins/target/target-workflow-var.go
  pkg/refactor/gateway2/plugins/target/target-workflow.go
  pkg/refactor/gateway2/router.go
  tests/events/workflow_events_or.test.js
  tests/gateway2/target_flow.test.js
  tests/gateway2/target_flow_var.test.js
  tests/gateway2/target_ns_file.test.js
  tests/gateway2/target_ns_var.test.js
  tests/services/system_services.test.js
Labels: backend, refactor

#1605 [DIR-1597] Fix for the parallel crons issue.
  pkg/flow/engine.go
  pkg/flow/routing.go
  pkg/refactor/database/db_schema.sql
  pkg/refactor/instancestore/instance.go
  pkg/refactor/instancestore/instance_test.go
  pkg/refactor/instancestore/instancestoresql/sql.go
Labels: bug, backend

#1611 [DIR-1240] test variables links when workflow deleted or renamed
  tests/part2/variables/workflow_link.test.js
Labels: testing, backend

#1584 [DIR-1585] Add test-case for application/cloudevents+json header type
  tests/events/events_v2.test.js
Labels: testing, backend

#1580 [DIR-1514] Migrate to events v2
  cmd/exec/cmd/events/events.go
Labels: cli, refactor

#1612 events tests fix
  tests/events/send_helper.js
Labels: bug, devops

#1613 Suppresses some spammy logs.
  pkg/refactor/api/sse_helper.go
  pkg/refactor/gateway/gateway.go
Labels: improvement, backend

#1567 [DIR-1576] fixes the fluent-bit configuration
  charts/direktiv/templates/flow/flow-secrets-fluentbit.yaml
  charts/direktiv/values.yaml
Labels: charts, devops

#1595 [DIR-1546] fix issue were logs might disappear
  ui/e2e/monitoring/index.spec.ts
  ui/src/api/logs/query/logs.ts
  ui/src/components/Logs/useLogVirtualizer.ts
  ui/src/design/Logs/index.tsx
  ui/src/util/helpers.ts
Labels: bug, ui

#1610 [DIR-1612 ] make playwright artifacts downloadable in CI
  .github/workflows/build.yml
Labels: devops

#1615 [DIR-1610] Fluentbit fix
  charts/direktiv/Chart.lock
  charts/direktiv/Chart.yaml
  charts/direktiv/charts/fluent-bit-0.43.0.tgz
  charts/direktiv/charts/fluent-bit-0.46.7.tgz
  charts/direktiv/values.yaml
  pkg/refactor/api/plattformlogs.go
  tests/part1/logs/basic_namespace_logs.test.js
  tests/part1/logs/gateway_logs.test.js
  tests/part1/logs/instance_logs.test.js
  tests/part1/logs/namespace_logs.test.js
  tests/part1/logs/sync_logs.test.js
Labels: bug, backend

#1609 [DIR-1604] Do not block navigation when only formatting has changed
  ui/e2e/explorer/route/index.spec.ts
  ui/src/pages/namespace/Explorer/Consumer/ConsumerEditor/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/index.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/index.tsx
Labels: bug, ui

#1616 [DIR-1613] fix service id generation to respect RFC 1123 subdomain
  .github/workflows/build.yml
  .golangci.yaml
  make_tests.mk
  pkg/refactor/core/service.go
  pkg/refactor/core/service_test.go
  pkg/refactor/service/service_test.go
  tests/services/action_workflow_and_run.test.js
Labels: bug, backend

#1618 House Keeping
  pkg/flow/grpc-instance-variables.go
  pkg/flow/grpc-instances.go
  pkg/flow/grpc-internal.go
  pkg/flow/grpc-namespace-variables.go
  pkg/flow/grpc-workflow-variables.go
Labels: refactor

#1617 [DIR-1583] Fix navigation via namespace selector with unsaved changes
  ui/e2e/explorer/workflow/codeEditor.spec.ts
  ui/src/components/Breadcrumb/NamespaceSelector.tsx
Labels: bug, ui

#1624 House Keeping: clean jest run command
  .github/workflows/build.yml
  docker-compose.yaml
  make_tests.mk
  tests/package.json
Labels: bug, backend

#1614 [DIR-1614] show services in the system namespace
  ui/e2e/services/list.spec.ts
  ui/e2e/utils/files.ts
  ui/e2e/utils/namespace.ts
  ui/src/api/files/mutate/deleteFile.ts
  ui/src/api/services/query/services.ts
  ui/src/api/services/schema/services.ts
  ui/src/pages/namespace/Explorer/Service/index.tsx
  ui/src/pages/namespace/Services/List/index.tsx
Labels: improvement, ui

#1622 [DIR-1511] Migrate tests to events v2
  pkg/refactor/api/events.go
  tests/events/send_events.test.js
  tests/events/send_helper.js
  tests/events/workflow_events.test.js
  tests/events/workflow_events_and.test.js
  tests/events/workflow_events_or.test.js
Labels: testing, backend

#1620 [DIR-1598] enable monitoring logs test and fix log deduplication
  ui/e2e/monitoring/index.spec.ts
  ui/src/api/logs/query/logs.ts
Labels: ui, testing

#1628 House Keeping: add raw endpoints
  .golangci.yaml
  cmd/direktiv/main.go
  pkg/refactor/api/filesystem.go
  pkg/refactor/api/variables.go
  pkg/refactor/gateway2/plugins/outbound/js.go
  pkg/refactor/gateway2/plugins/target/target-ns-file.go
  pkg/refactor/gateway2/plugins/target/target-ns-var.go
  pkg/refactor/gateway2/plugins/target/target-workflow-var.go
  tests/events/send_events.test.js
  tests/events/workflow_events.test.js
  tests/events/workflow_events_or.test.js
  tests/gateway2/target_flow_var.test.js
  tests/gateway2/target_ns_file.test.js
  tests/gateway2/target_ns_var.test.js
  tests/part1/filesystem/read_file_v2.test.js
  tests/part2/variables/basic_crud.test.js
  ui/conf/nginx.conf
Labels: backend, refactor

#1629 Chart Version Update
  charts/direktiv/Chart.yaml
Labels: charts

#1631 [DIR-1616] Fix events-error handling
  pkg/refactor/api/events.go
  pkg/refactor/datastore/datastoresql/eventstore_history.go
  tests/events/events_v2.test.js
  tests/events/send_events.test.js
Labels: bug, backend

#1632 [DIR-1617] Migrate test-case to new API endpoints
  tests/events/workflow_events_and.test.js
Labels: testing, backend

#1630 [DIR-1591] remove v1 api entirely
  charts/direktiv/templates/flow/flow-deployment.yaml
  charts/direktiv/templates/flow/flow-service.yaml
  docker-compose.yaml
  pkg/api/entry.go
  pkg/api/error.go
  pkg/api/flow.go
  pkg/api/metrics.go
  pkg/api/routes.go
  pkg/api/server.go
  pkg/api/util.go
  pkg/refactor/api/api.go
  pkg/refactor/cmd/main.go
  pkg/refactor/core/app.go
  pkg/refactor/gateway/plugins/target/target-ns-file.go
  pkg/refactor/gateway/plugins/target/target-ns-var.go
  pkg/refactor/gateway/plugins/target/target-workflow.go
  pkg/refactor/gateway2/plugins/target/target-ns-file.go
  pkg/refactor/gateway2/plugins/target/target-ns-var.go
  pkg/refactor/gateway2/plugins/target/target-workflow-var.go
  pkg/refactor/gateway2/plugins/target/target-workflow.go
  tests/kubernetes/generic-container.test.js
  tests/part1/errors/not_found.test.js
Labels: backend

#1639 House Keeping
  .golangci.yaml
  cmd/sidecar/local-server.go
  cmd/sidecar/main.go
  cmd/sidecar/network-server.go
  cmd/sidecar/worker.go
  pkg/cmd/main.go
  pkg/datastore/datastoresql/mirror.go
  pkg/datastore/datastoresql/secrets.go
  pkg/filestore/path.go
  pkg/flow/grpc-flow.go
  pkg/flow/grpc-internal.go
  pkg/flow/routing.go
  pkg/flow/server.go
  pkg/flow/states/action-helpers.go
  pkg/flow/states/getter.go
  pkg/flow/states/setter.go
  pkg/flow/temporary.go
  pkg/gateway/plugins/target/request.go
  pkg/gateway2/plugins/target/request.go
  pkg/instancestore/instance.go
  pkg/instancestore/instance_test.go
  pkg/model/function-namespaced.go
  pkg/model/function-reusable.go
  pkg/model/function-subflow.go
  pkg/model/function-system.go
  pkg/model/state-common.go
  pkg/model/state-getter.go
  pkg/model/state-setter.go
  pkg/service/helper.go
  pkg/util/callers.go
  pkg/util/env.go
  pkg/utils/encrypt.go
  pkg/utils/grpc-util.go
  pkg/utils/instance.go
  pkg/utils/regex.go
  pkg/utils/telemetry.go
  pkg/utils/vars.go
Labels: backend, refactor

#1641 House Keeping
  pkg/flow/bytedata/data.go
  pkg/flow/events.go
  pkg/flow/grpc-internal.go
  pkg/flow/grpc/cloudevent.pb.go
  pkg/flow/grpc/cloudevent.proto
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
  pkg/flow/pubsub/pubsub.go
  pkg/flow/trace.go
  pkg/utils/data.go
Labels: backend, refactor

#1644 [DIR-1622] refactor logging
  pkg/engine/telemetry.go
  pkg/events/eventworker.go
  pkg/events/process.go
  pkg/events/process_test.go
  pkg/flow/db-events.go
  pkg/flow/engine.go
  pkg/flow/events.go
  pkg/flow/grpc-internal.go
  pkg/flow/instance_messages.go
  pkg/flow/pubsub/pubsub.go
  pkg/flow/status.go
  pkg/flow/temporary.go
  pkg/tracing/context_builder.go
  tests/events/workflow_events_complex.test.js
Labels: improvement, backend

#1645 [DIR-1633] Add namespace attr builder for logs
  pkg/tracing/context_builder.go
Labels: backend, refactor
