Repository direktiv/direktiv, pull requests merged in 2024-04, with the labels that each got.

#1384 [DIR-1391] implement namespace api v2
  pkg/refactor/api/namespaces.go
  tests/namespaces/basic_create.test.js
  tests/namespaces/basic_crud.test.js
  tests/namespaces/basic_delete.test.js
  tests/namespaces/basic_update.test.js
  tests/namespaces/structure.test.js
Labels: backend

#1402 [DIR-1406] bug fix variables api v2
  openapi/src/paths/paths.yaml
  openapi/src/paths/variables.yaml
  pkg/refactor/api/variables.go
  tests/variables2/basic_create.test.js
  tests/variables2/basic_update.test.js
  tests/variables2/structure.test.js
Labels: bug, backend

#1404 [DIR-1406] bug fix variables api v2
  pkg/refactor/api/variables.go
  tests/variables2/list.js
Labels: bug, backend

#1399 [DIR-1409] fix(chart): remove hard-coded envs
  charts/direktiv/templates/flow/flow-deployment.yaml
Labels: charts

#1408 [DIR-1048] Fix mirroring object in namespace api v2
  pkg/refactor/datastore/mirrors.go
  tests/namespaces/basic_create.test.js
  tests/namespaces/basic_crud.test.js
  tests/namespaces/basic_update.test.js
  tests/namespaces/structure.test.js
Labels: bug, backend

#1409 [DIR-1414] implement mirroring api v2
  pkg/flow/server.go
  pkg/refactor/api/api.go
  pkg/refactor/api/mirrors.go
  pkg/refactor/api/namespaces.go
  pkg/refactor/cmd/main.go
  pkg/refactor/core/app.go
  pkg/refactor/datastore/datastoresql/mirror.go
Labels: bug, backend

#1413 [DIR-1415] Remove internal events
  pkg/flow/broadcast.go
  pkg/flow/engine.go
  pkg/flow/grpc-nodes.go
  pkg/flow/grpc-workflow.go
Labels: backend, refactor

#1412 [DIR-1411] Remove router dependency from storybook
  ui/src/components/NavigationBlocker/index.tsx
  ui/src/design/Editor/index.tsx
  ui/src/pages/namespace/Explorer/Consumer/ConsumerEditor/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/index.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/index.tsx
  ui/src/pages/namespace/Explorer/Workflow/Edit/CodeEditor.tsx
Labels: bug, ui

#1396 [DIR-1394] E2E Test Instance Page Header
  ui/e2e/instances/details/index.spec.ts
  ui/src/pages/namespace/Instances/Detail/Header/index.tsx
Labels: ui, testing

#1411 [DIR-1412] Save files when clicking save in a subform
  ui/e2e/explorer/route/index.spec.ts
  ui/e2e/explorer/service/index.spec.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Auth/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Inbound/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Outbound/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/plugins/target/schema.ts
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/Form/Patches/index.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/Form/index.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/index.tsx
Labels: improvement, ui

#1414 [DIR-1336] correctly display v2 api errors when saving workflows
  ui/e2e/explorer/workflow/codeEditor.spec.ts
  ui/src/api/errorHandling.ts
Labels: bug, ui

#1416 [DIR-1414] implement mirroring api v2
  openapi/src/openapi.yaml
  openapi/src/paths/namespaces.yaml
  openapi/src/paths/paths.yaml
  pkg/refactor/api/namespaces.go
  pkg/refactor/datastore/mirrors.go
  tests/namespaces/basic_create.test.js
  tests/namespaces/basic_crud.test.js
  tests/namespaces/basic_update.test.js
  tests/namespaces/structure.test.js
Labels: backend

#1417 [dir-1414] implement mirroring api v2
  openapi/src/openapi.yaml
  openapi/src/paths/paths.yaml
  openapi/src/paths/syncs.yaml
  pkg/refactor/datastore/mirrors.go
Labels: backend

#1407 [DIR-1413] Fix invalid knative env vars in helm charts.
  charts/direktiv/templates/flow/flow-deployment.yaml
  charts/direktiv/templates/frontend/frontend-deployment.yaml
Labels: bug, backend

#1418 [DIR-1419] cleanups
  .golangci.yaml
  pkg/api/entry.go
  pkg/api/server.go
  pkg/flow/server.go
  pkg/refactor/api/api.go
  pkg/refactor/cmd/main.go
  ui/Makefile
Labels: backend, refactor

#1422 [DIR-1407] Fix creating duplicated variables bug.
  docker-compose.yaml
  pkg/refactor/api/errors.go
  pkg/refactor/database/database.go
  pkg/refactor/database/db_schema.sql
  pkg/refactor/datastore/datastore.go
  pkg/refactor/datastore/datastoresql/runtime_variables.go
  tests/variables2/no_duplicated.test.js
Labels: bug, backend

#1420 [DIR-1422] Should resolve DIR-1422.
  pkg/jqer/jqer.go
Labels: bug, backend

#1415 [DIR-1418] Elevate instance crash msg
  pkg/flow/engine.go
Labels: bug, backend

#1425 [DIR-1419] implement graceful shutdown
  Makefile
  cmd/direktiv/flow.go
  pkg/flow/server.go
  pkg/refactor/api/api.go
  pkg/refactor/cmd/main.go
  pkg/refactor/core/circuit.go
  pkg/refactor/core/service.go
  pkg/refactor/pubsub/pubsub_pg.go
  pkg/refactor/service/manager.go
Labels: backend, refactor

#1426 [DIR-1419] cleanup db types in legacy code
  pkg/flow/db-events.go
  pkg/flow/engine.go
  pkg/flow/eventing.go
  pkg/flow/events.go
  pkg/flow/grpc-flow.go
  pkg/flow/grpc-instances.go
  pkg/flow/grpc-internal.go
  pkg/flow/grpc-linters.go
  pkg/flow/grpc-mirror.go
  pkg/flow/grpc-namespaces.go
  pkg/flow/grpc-nodes.go
  pkg/flow/grpc-workflow-variables.go
  pkg/flow/memory.go
  pkg/flow/nohome/cache.go
  pkg/flow/nohome/database.go
  pkg/flow/nohome/recipient/recipient.go
  pkg/flow/pubsub/pubsub.go
  pkg/flow/routing.go
  pkg/flow/secrets.go
  pkg/flow/server.go
  pkg/flow/temporary.go
  pkg/flow/trace.go
  pkg/refactor/api/api.go
  pkg/refactor/api/filesystem.go
  pkg/refactor/api/instances.go
  pkg/refactor/api/mirrors.go
  pkg/refactor/api/namespaces.go
  pkg/refactor/api/secrets.go
  pkg/refactor/api/variables.go
  pkg/refactor/cmd/main.go
  pkg/refactor/core/app.go
  pkg/refactor/database/database.go
  pkg/refactor/engine/telemetry.go
  pkg/refactor/gateway/gateway.go
  pkg/refactor/gateway/gateway_test.go
  pkg/refactor/gateway/plugins/plugin.go
  scripts/build/docker/all/docker/installer/main.go
Labels: bug, backend

#1428 [DIR-1428] fix sorting bug
  openapi/src/paths/paths.yaml
  openapi/src/paths/secrets.yaml
  pkg/refactor/datastore/datastoresql/runtime_variables.go
Labels: bug, backend

#1431 [DIR-1428] Fix sorting secrets api v2
  pkg/refactor/datastore/datastoresql/secrets.go
Labels: bug, backend

#1432 [DIR-1428] Fix missed initialized field in secrets api v2
  pkg/refactor/api/secrets.go
  tests/secrets2/basic_create.test.js
  tests/secrets2/basic_crud.test.js
  tests/secrets2/basic_update.test.js
  tests/secrets2/structure.test.js
Labels: bug, backend

#1435 [DIR-1436] add query string name filter to listing variables endpoint
  openapi/src/paths/paths.yaml
  openapi/src/paths/variables.yaml
  pkg/refactor/api/variables.go
  tests/common/helpers.js
  tests/variables2/list.test.js
  tests/variables2/list_wih_filters.test.js
Labels: feature, backend

#1436 [DIR-1439] remove gitcommithash field from v2 api namespace mirrors
  openapi/src/paths/namespaces.yaml
  openapi/src/paths/paths.yaml
  pkg/flow/bytedata/data2.go
  pkg/flow/grpc/mirror.pb.go
  pkg/flow/grpc/mirror.proto
  pkg/refactor/api/namespaces.go
  pkg/refactor/database/db_schema.sql
  pkg/refactor/datastore/datastoresql/mirror.go
  pkg/refactor/datastore/mirrors.go
  pkg/refactor/mirror/apply.go
  pkg/refactor/mirror/source.go
  tests/mirror/mirror.test.js
  tests/namespaces/basic_create.test.js
  tests/namespaces/basic_update.test.js
Labels: bug, backend

#1437 [DIR-1437] add token field to v2 api namespace mirror
  openapi/src/paths/namespaces.yaml
  openapi/src/paths/paths.yaml
  pkg/refactor/database/db_schema.sql
  pkg/refactor/datastore/datastoresql/mirror.go
  pkg/refactor/datastore/mirrors.go
  pkg/refactor/mirror/source.go
  tests/namespaces/basic_create.test.js
Labels: bug, backend

#1438 [DIR-1438] make v2 api namespaces patchable
  openapi/src/paths/namespaces.yaml
  openapi/src/paths/paths.yaml
  pkg/refactor/api/namespaces.go
  pkg/refactor/datastore/datastoresql/mirror.go
  pkg/refactor/datastore/mirrors.go
  tests/namespaces/basic_update.test.js
  tests/variables2/list_wih_filters.test.js
  tests/variables2/no_duplicated.test.js
Labels: bug, backend

#1443 [DIR-1422] Prevents jq/js engine from leaking object information.
  pkg/jqer/jqer.go
  pkg/jqer/jqer_test.go
Labels: bug, backend

#1444 [DIR-1437] Fix openapi docs
  openapi/src/paths/paths.yaml
  openapi/src/paths/syncs.yaml
Labels: bug, backend

#1424 [DIR-1423] Fix context filter matching
  pkg/flow/db-events.go
  pkg/refactor/events/events.go
  pkg/refactor/events/eventworker.go
  pkg/refactor/events/glob_test.go
  pkg/refactor/events/process.go
  pkg/refactor/events/process_test.go
  tests/events/send_helper.js
  tests/events/workflow_events.test.js
  tests/events/workflow_events_and.test.js
  tests/events/workflow_events_complex.test.js
Labels: bug, backend

#1445 [DIR-1441] Fix broken creation of depricated vriables in mirroring logic
  pkg/refactor/mirror/apply.go
Labels: bug, backend

#1331 [DIR-710] Enhancing UX for Time Input in Filters
  ui/public/locales/en/translation.json
  ui/src/components/Filters/DatePicker.tsx
  ui/src/components/Filters/RefineTime.tsx
  ui/src/components/Filters/SelectFieldMenu.tsx
  ui/src/components/Filters/TextInput.tsx
  ui/src/design/Timepicker/Input.tsx
  ui/src/design/Timepicker/__tests__/utils.test.ts
  ui/src/design/Timepicker/index.stories.tsx
  ui/src/design/Timepicker/index.tsx
  ui/src/design/Timepicker/utils.ts
  ui/src/pages/namespace/Events/History/components/Filters/DatePicker.tsx
  ui/src/pages/namespace/Events/History/components/Filters/RefineTime.tsx
  ui/src/pages/namespace/Events/History/components/Filters/SelectFieldMenu.tsx
  ui/src/pages/namespace/Events/History/components/Filters/TextInput.tsx
  ui/src/pages/namespace/Events/History/components/Filters/index.tsx
  ui/src/pages/namespace/Instances/components/Filters/SelectFieldMenu.tsx
  ui/src/pages/namespace/Instances/components/Filters/index.tsx
Labels: improvement, ui

#1442 [DIR-1330] Changes various gateway plugins to use v2 apis.
  pkg/refactor/gateway/plugins/plugin.go
  pkg/refactor/gateway/plugins/target/request.go
  pkg/refactor/gateway/plugins/target/target-ns-file.go
  pkg/refactor/gateway/plugins/target/target-ns-var.go
  pkg/refactor/gateway/plugins/target/target-workflow-var.go
  pkg/refactor/gateway/plugins/target/target-workflow.go
Labels: backend

#1430 [DIR-1420] Adding E2E Test for Instances Details - Diagram
  ui/e2e/instances/details/index.spec.ts
  ui/e2e/instances/utils/workflows.ts
  ui/src/pages/namespace/Instances/Detail/Main/Diagram/index.tsx
Labels: ui, testing

#1448 [DIR-1446] Improve mimetype handling
  pkg/refactor/gateway/plugins/target/target-ns-file.go
  tests/gateway/target_file.test.js
Labels: improvement, gateway

#1401 [DIR-1055] migrate to v2 variable API
  ui/e2e/explorer/workflow/settings.spec.ts
  ui/e2e/explorer/workflow/utils.ts
  ui/e2e/settings/index.spec.ts
  ui/e2e/utils/variables.ts
  ui/public/locales/en/translation.json
  ui/src/api/apiFactory.ts
  ui/src/api/schema.ts
  ui/src/api/tree/mutate/downloadVariable.ts
  ui/src/api/tree/mutate/setVariable.ts
  ui/src/api/tree/query/variableContent.ts
  ui/src/api/tree/query/variables.ts
  ui/src/api/tree/schema/workflowVariable.ts
  ui/src/api/variables/index.ts
  ui/src/api/variables/mutate/create.ts
  ui/src/api/variables/mutate/delete.ts
  ui/src/api/variables/mutate/download.ts
  ui/src/api/variables/mutate/update.ts
  ui/src/api/variables/query/details.ts
  ui/src/api/variables/query/get.ts
  ui/src/api/variables/query/useVariableContent.ts
  ui/src/api/variables/schema.ts
  ui/src/components/NamespaceVariablepicker/index.tsx
  ui/src/components/VariableForm/CreateForm.tsx
  ui/src/components/VariableForm/EditForm.tsx
  ui/src/components/VariableForm/FileUpload/__tests__/utils.test.ts
  ui/src/components/VariableForm/FileUpload/index.tsx
  ui/src/components/VariableForm/FileUpload/utils.ts
  ui/src/components/VariableForm/MimeTypeSelect.tsx
  ui/src/components/VariableForm/index.tsx
  ui/src/components/VariableForm/utils.ts
  ui/src/components/WorkflowVariablepicker/index.tsx
  ui/src/pages/namespace/Explorer/Workflow/Settings/Variables/Create.tsx
  ui/src/pages/namespace/Explorer/Workflow/Settings/Variables/Edit.tsx
  ui/src/pages/namespace/Explorer/Workflow/Settings/Variables/index.tsx
  ui/src/pages/namespace/Settings/Secrets/CreateEdit.tsx
  ui/src/pages/namespace/Settings/Variables/Create.tsx
  ui/src/pages/namespace/Settings/Variables/Edit.tsx
  ui/src/pages/namespace/Settings/Variables/MimeTypeSelect.tsx
  ui/src/pages/namespace/Settings/Variables/index.tsx
  ui/src/pages/namespace/Settings/index.tsx
  ui/src/util/helpers.ts
Labels: improvement, ui

#1429 [DIR-1405] migrate to v2 secrets API
  ui/e2e/notificationmenu/index.spec.ts
  ui/e2e/settings/index.spec.ts
  ui/e2e/utils/secrets.ts
  ui/public/locales/en/translation.json
  ui/src/api/secrets/index.ts
  ui/src/api/secrets/mutate/create.ts
  ui/src/api/secrets/mutate/delete.ts
  ui/src/api/secrets/mutate/update.ts
  ui/src/api/secrets/query/get.ts
  ui/src/api/secrets/schema.ts
  ui/src/components/FileUpload/__tests__/utils.test.ts
  ui/src/components/FileUpload/index.tsx
  ui/src/components/FileUpload/utils.ts
  ui/src/components/VariableForm/index.tsx
  ui/src/pages/namespace/Settings/Secrets/Create.tsx
  ui/src/pages/namespace/Settings/Secrets/CreateEdit.tsx
  ui/src/pages/namespace/Settings/Secrets/Delete.tsx
  ui/src/pages/namespace/Settings/Secrets/Edit.tsx
  ui/src/pages/namespace/Settings/Secrets/Form/index.tsx
  ui/src/pages/namespace/Settings/Secrets/index.tsx
Labels: improvement, ui

#1427 [DIR-1056] [DIR-1054] remove legacy v1 variable apis
  .github/workflows/api-e2e.yml
  .github/workflows/k3s-e2e-tests.yml
  cmd/exec/cmd/workflows/workflows.go
  pkg/api/flow.go
  pkg/flow/bytedata/data2.go
  pkg/flow/grpc-instance-variables.go
  pkg/flow/grpc-namespace-variables.go
  pkg/flow/grpc-workflow-variables.go
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
  pkg/flow/grpc/variables.pb.go
  pkg/flow/grpc/variables.proto
  pkg/flow/server.go
  pkg/refactor/api/namespaces.go
  tests/events/workflow_events.test.js
  tests/events/workflow_events_and.test.js
  tests/events/workflow_events_complex.test.js
  tests/functions/files.test.js
  tests/gateway/target_file.test.js
  tests/gateway/target_ns_var.test.js
  tests/gateway/target_wf_var.test.js
  tests/mirror/mirror.test.js
  tests/namespaces/structure.test.js
  tests/variables/basic_create.test.js
  tests/variables/basic_crud.test.js
  tests/variables/basic_delete.test.js
  tests/variables/basic_update.test.js
  tests/variables/instvars.test.js
  tests/variables/list.test.js
  tests/variables/list_wih_filters.test.js
  tests/variables/no_duplicated.test.js
  tests/variables/nsvars.test.js
  tests/variables/structure.test.js
  tests/variables/wfvars.test.js
Labels: backend, refactor

#1452 [DIR-1450] remove secretes v1 api
  .github/workflows/k3s-e2e-tests.yml
  Makefile
  pkg/api/flow.go
  pkg/flow/bytedata/data2.go
  pkg/flow/grpc-secrets.go
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
  pkg/flow/grpc/secrets.pb.go
  pkg/flow/grpc/secrets.proto
  tests/gateway/target_wf_var.test.js
  tests/secrets/basic_create.test.js
  tests/secrets/basic_crud.test.js
  tests/secrets/basic_delete.test.js
  tests/secrets/basic_update.test.js
  tests/secrets/secrets_crud_operations.test.js
  tests/secrets/secrets_read.test.js
  tests/secrets/structure.test.js
Labels: backend, refactor

#1451 [DIR-1404] Split makefile
  .github/workflows/api-e2e.yml
  .github/workflows/go-licenses.yml
  .gitignore
  Makefile
  make_direktiv.mk
  make_direktiv_ui.mk
  make_k3s.mk
  make_protobuf.mk
  make_tests.mk
Labels: devops

#1454 Fixes and reintroduces the make help command to our newly divided mak…
  Makefile
Labels: devops

#1449 [DIR-1378] Disabling the Run Button in the header on unsaved Changes
  ui/e2e/explorer/workflow/run.spec.ts
  ui/src/pages/namespace/Explorer/Workflow/Edit/WorkflowEditor.tsx
  ui/src/pages/namespace/Explorer/Workflow/index.tsx
  ui/src/pages/namespace/Explorer/Workflow/store/type.ts
  ui/src/pages/namespace/Explorer/Workflow/store/unsavedChangesContext.tsx
  ui/src/pages/namespace/Explorer/index.tsx
Labels: bug, ui

#1457 [DIR-1438] add auth type field
  Makefile
  make_composer.mk
  openapi/src/paths/namespaces.yaml
  openapi/src/paths/paths.yaml
  pkg/refactor/api/namespaces.go
  pkg/refactor/datastore/mirrors.go
  tests/namespaces/basic_create.test.js
  tests/namespaces/basic_update.test.js
Labels: feature, backend

#1458 [DIR-1438] add namespace input field authType
  openapi/src/paths/namespaces.yaml
  openapi/src/paths/paths.yaml
  pkg/refactor/api/errors.go
  pkg/refactor/api/namespaces.go
  pkg/refactor/database/db_schema.sql
  pkg/refactor/datastore/datastore.go
  pkg/refactor/datastore/datastoresql/mirror.go
  pkg/refactor/datastore/mirror_test.go
  pkg/refactor/datastore/mirrors.go
  tests/namespaces/basic_create.test.js
  tests/namespaces/basic_update.test.js
Labels: feature, backend

#1459 Minor fixes
  openapi/src/openapi.yaml
  pkg/refactor/api/namespaces.go
  pkg/refactor/datastore/datastoresql/mirror.go
  pkg/refactor/datastore/mirrors.go
  tests/namespaces/basic_create.test.js
  tests/namespaces/basic_update.test.js
Labels: bug, backend

#1461 Normalize workflow path of variables
  pkg/refactor/datastore/datastoresql/runtime_variables.go
Labels: bug, backend

#1460 [DIR-1451] add payload type support to api factory
  ui/e2e/utils/events.ts
  ui/e2e/utils/files.ts
  ui/src/api/apiFactory.ts
  ui/src/api/enterprise/groups/mutation/create.ts
  ui/src/api/enterprise/groups/mutation/edit.ts
  ui/src/api/enterprise/policy/mutate/update.ts
  ui/src/api/enterprise/tokens/mutate/create.ts
  ui/src/api/events/mutate/sendEvent.ts
  ui/src/api/files/mutate/createFile.ts
  ui/src/api/files/mutate/patchFile.ts
  ui/src/api/jq/mutate/executeQuery.ts
  ui/src/api/namespaces/mutate/createNamespace.ts
  ui/src/api/registries/mutate/createRegistry.ts
  ui/src/api/secrets/mutate/create.ts
  ui/src/api/secrets/mutate/update.ts
  ui/src/api/tree/mutate/runWorkflow.ts
  ui/src/api/variables/mutate/update.ts
Labels: improvement, ui

#1465 [DIR-1447] Migrates the linting api to the v2 api, and renames it to notifications.
  .github/workflows/k3s-e2e-tests.yml
  openapi/src/openapi.yaml
  openapi/src/paths/notifications.yaml
  pkg/refactor/api/api.go
  pkg/refactor/api/notifications.go
  tests/notifications/uninitialized_secrets.test.js
Labels: backend

#1466 [DIR-1459] Fix % not escaped in logs
  pkg/flow/engine.go
Labels: bug, backend

#1467 [DIR-1464] Fix mirroring with auth token
  pkg/refactor/mirror/source.go
Labels: bug, backend

#1470 [DIR-1467] error messages are less helpful with unclear error codes
  pkg/flow/engine.go
Labels: bug, backend

#1469 [DIR-1452] event type containing spaces is causing problems
  pkg/refactor/datastore/datastoresql/eventstore.go
Labels: bug, backend

#1476 Makes error message more consistent and fixes an e2e test as a result.
  pkg/refactor/api/notifications.go
Labels: bug, backend

#1474 [DIR-1473] Adds a namespace ID argument to the AssertNoParallelCron instancestor…
  pkg/flow/routing.go
  pkg/refactor/instancestore/instance.go
  pkg/refactor/instancestore/instance_test.go
  pkg/refactor/instancestore/instancestoresql/sql.go
Labels: bug, backend

#1475 [DIR-1472] Implements a v2 metrics API to replace the v1.
  .github/workflows/k3s-e2e-tests.yml
  openapi/src/openapi.yaml
  openapi/src/paths/metrics.yaml
  pkg/refactor/api/api.go
  pkg/refactor/api/metrics.go
  pkg/refactor/instancestore/instance.go
  pkg/refactor/instancestore/instance_test.go
  pkg/refactor/instancestore/instancestoresql/sql.go
  tests/metrics/workflow_metrics.test.js
Labels: backend, refactor

#1479 [DIR-1480] soft delete grpc eventing server
  charts/direktiv/README.md
  charts/direktiv/templates/eventing.yaml
  charts/direktiv/templates/flow/flow-deployment.yaml
  charts/direktiv/templates/flow/flow-service.yaml
  charts/direktiv/values.yaml
  pkg/flow/eventing.go
  pkg/flow/events.go
  pkg/flow/grpc/eventing.pb.go
  pkg/flow/grpc/eventing.proto
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
  pkg/flow/server.go
  pkg/refactor/core/app.go
Labels: backend

#1480 Clean unused code
  pkg/flow/grpc-namespaces.go
  pkg/flow/grpc/namespaces.pb.go
  pkg/flow/grpc/namespaces.proto
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
Labels: bug, backend

#1472 [DIR-1468] Render error messages in logs
  ui/public/locales/en/translation.json
  ui/src/components/Logs/utils.ts
  ui/src/pages/namespace/Gateway/Routes/Detail/Logs/Entry.tsx
  ui/src/pages/namespace/Instances/Detail/Main/Logs/Entry.tsx
  ui/src/pages/namespace/Mirror/Activities/Detail/Logs/Entry.tsx
  ui/src/pages/namespace/Monitoring/Logs/Entry.tsx
Labels: bug, ui

#1473 [DIR-1449] [DIR-1304] Remove a legacy api dependency from UI
  ui/src/api/tree/index.ts
  ui/src/api/tree/query/node.ts
  ui/src/pages/namespace/Services/Detail/Scale.tsx
Labels: ui

#1483 Fix missing variables implementation
  pkg/flow/grpc-flow.go
  pkg/flow/grpc-instance-variables.go
  pkg/flow/grpc-internal.go
  pkg/flow/grpc-namespace-variables.go
  pkg/flow/grpc-workflow-variables.go
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
  pkg/flow/grpc/variables.pb.go
  pkg/flow/grpc/variables.proto
  tests/functions/files.test.js
Labels: bug, backend

#1481 [DIR-1476] Remove v1 filesystem api dependencies from e2e tests
  ui/e2e/explorer/index.spec.ts
  ui/e2e/explorer/workflow/codeEditor.spec.ts
  ui/e2e/utils/files.ts
  ui/e2e/utils/node.ts
  ui/e2e/utils/workflow.ts
  ui/src/api/files/query/file.ts
Labels: ui

#1485 [DIR-1485] Removes most Go code references to the LogToEvents and Instance Settings
  pkg/flow/engine.go
  pkg/refactor/engine/instance.go
  pkg/refactor/engine/settings.go
  pkg/refactor/instancestore/instance.go
  pkg/refactor/instancestore/instance_data_query_test.go
  pkg/refactor/instancestore/instance_test.go
  pkg/refactor/instancestore/instancestoresql/instancestoresql_test.go
  pkg/refactor/instancestore/instancestoresql/sql.go
Labels: backend, refactor

#1486 [DIR-1487] Removes metrics from the flow package.
  pkg/api/flow.go
  pkg/api/metrics.go
  pkg/flow/engine.go
  pkg/flow/events.go
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
  pkg/flow/grpc/util.pb.go
  pkg/flow/grpc/util.proto
  pkg/flow/metrics.go
  pkg/flow/scheduling.go
  pkg/flow/server.go
  pkg/metrics/metrics.go
  pkg/metrics/types.go
Labels: backend, refactor

#1477 [DIR-1454] Improves instances v2 APIs.
  openapi/src/objects.yaml
  openapi/src/paths/instances.yaml
  openapi/src/paths/paths.yaml
  pkg/refactor/api/instances.go
  pkg/refactor/instancestore/instance.go
  pkg/refactor/instancestore/instance_data_query_test.go
  pkg/refactor/instancestore/instancestoresql/sql.go
  tests/instances/blobs.test.js
  tests/instances/cancel.test.js
  tests/instances/wait-success.test.js
Labels: backend

#1463 [DIR-1396] Adds a system-level knative service.
  pkg/flow/temporary.go
  pkg/model/function-common.go
  pkg/model/function-system.go
  pkg/refactor/cmd/main.go
  pkg/refactor/core/service.go
Labels: feature, backend

#1490 [DIR-1500] Fixes and suppresses many common linter complaints.
  pkg/flow/bytedata/data.go
  pkg/flow/cancel.go
  pkg/flow/db-events.go
  pkg/flow/engine.go
  pkg/flow/errors/internal.go
  pkg/flow/errors/notFound.go
  pkg/flow/eventing.go
  pkg/flow/events.go
  pkg/flow/grpc-flow.go
  pkg/flow/grpc-instance-variables.go
  pkg/flow/grpc-instances.go
  pkg/flow/grpc-internal.go
  pkg/flow/grpc-linters.go
  pkg/flow/grpc-mirror.go
  pkg/flow/grpc-namespace-variables.go
  pkg/flow/grpc-namespaces.go
  pkg/flow/grpc-workflow-variables.go
  pkg/flow/instance_messages.go
  pkg/flow/jq.go
  pkg/flow/memory.go
  pkg/flow/nohome/database.go
  pkg/flow/pubsub/pubsub.go
  pkg/flow/routing.go
  pkg/flow/scheduling.go
  pkg/flow/server.go
  pkg/flow/state-logic.go
  pkg/flow/states/action-helpers.go
  pkg/flow/states/action.go
  pkg/flow/states/consumeEvent.go
  pkg/flow/states/delay.go
  pkg/flow/states/error.go
  pkg/flow/states/eventsAnd.go
  pkg/flow/states/eventsXor.go
  pkg/flow/states/foreach.go
  pkg/flow/states/generateEvent.go
  pkg/flow/states/getter.go
  pkg/flow/states/helpers.go
  pkg/flow/states/instance.go
  pkg/flow/states/noop.go
  pkg/flow/states/parallel.go
  pkg/flow/states/setter.go
  pkg/flow/states/switch.go
  pkg/flow/states/validate.go
  pkg/flow/temporary.go
  pkg/flow/timeouts.go
  pkg/flow/trace.go
Labels: backend, refactor

#1489 [DIR-1051] remove legacy v1 namespace apis
  go.mod
  go.sum
  pkg/api/flow.go
  pkg/api/util.go
  pkg/flow/bytedata/data2.go
  pkg/flow/bytedata/data_test.go
  pkg/flow/grpc-mirror.go
  pkg/flow/grpc-namespaces.go
  pkg/flow/grpc/mirror.pb.go
  pkg/flow/grpc/mirror.proto
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
  pkg/flow/mockdata/entlog_loop.json
  pkg/flow/mockdata/entlog_loopFunctionNested.json
  pkg/flow/mockdata/entlog_nestedLoop.json
  pkg/refactor/events/glob_test.go
  tests/.eslintrc
  tests/babel.config.js
  tests/common/helpers.js
  tests/common/retry.js
  tests/common/structs.js
  tests/engine/cancel.test.js
  tests/engine/catch.test.js
  tests/engine/error-state.test.js
  tests/engine/getter-setter.test.js
  tests/engine/instance-data.test.js
  tests/engine/noop.test.js
  tests/engine/simple-chain.test.js
  tests/engine/simple-events.test.js
  tests/engine/simple-loop.test.js
  tests/engine/simple-subflow.test.js
  tests/events/send_events.test.js
  tests/events/send_helper.js
  tests/events/workflow_events.test.js
  tests/events/workflow_events_and.test.js
  tests/events/workflow_events_complex.test.js
  tests/events/workflow_events_or.test.js
  tests/filesystem/update_file_v2.test.js
  tests/functions/files.test.js
  tests/gateway/endpoints_crud.test.js
  tests/instances/blobs.test.js
  tests/instances/cancel.test.js
  tests/instances/wait-fail.test.js
  tests/instances/wait-success.test.js
  tests/jest.config.js
  tests/logparser/callpath.test.js
  tests/metrics/workflow_metrics.test.js
  tests/namespaces/namespaces_git_mirror.test.js
  tests/notifications/uninitialized_secrets.test.js
  tests/secrets/secrets_read.test.js
  tests/services/action_workflow_and_run.test.js
  tests/services/env_variables.test.js
  tests/services/git_mirror_with_services.test.js
Labels: backend, refactor

#1493 [DIR-1504] Fix broken /namespaces/lint endpoint
  openapi/src/openapi.yaml
  openapi/src/paths/instances.yaml
  openapi/src/paths/paths.yaml
  pkg/api/flow.go
  tests/instances/blobs.test.js
  tests/instances/cancel.test.js
  tests/instances/wait-success.test.js
Labels: bug, backend

#1456 [DIR-937] update TanStack Query to Version 5
  ui/package.json
  ui/src/api/__tests__/apiFactory.test.ts
  ui/src/api/enterprise/groups/mutation/create.ts
  ui/src/api/enterprise/groups/mutation/edit.ts
  ui/src/api/enterprise/policy/mutate/update.ts
  ui/src/api/enterprise/tokens/mutate/create.ts
  ui/src/api/files/mutate/deleteFile.ts
  ui/src/api/files/mutate/renameFile.ts
  ui/src/api/files/mutate/updateFile.ts
  ui/src/api/logs/query/logs.ts
  ui/src/api/namespaces/mutate/createNamespace.ts
  ui/src/api/namespaces/mutate/deleteNamespace.ts
  ui/src/api/namespaces/mutate/updateNamespace.ts
  ui/src/api/registries/mutate/createRegistry.ts
  ui/src/api/secrets/mutate/create.ts
  ui/src/api/secrets/mutate/delete.ts
  ui/src/api/secrets/mutate/update.ts
  ui/src/api/services/mutate/rebuild.ts
  ui/src/api/syncs/mutate/sync.ts
  ui/src/api/useInfiniteQueryWithPermissions.ts
  ui/src/api/useMutationWithPermissions.ts
  ui/src/api/useQueryWithPermissions.ts
  ui/src/api/variables/mutate/create.ts
  ui/src/api/variables/mutate/delete.ts
  ui/src/api/variables/mutate/update.ts
  ui/src/components/Authdialog/index.tsx
  ui/src/components/NamespaceEdit/index.tsx
  ui/src/pages/namespace/Explorer/Consumer/ConsumerEditor/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/index.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/index.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Directory.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Gateway/Consumer.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Gateway/Route.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Service/index.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Workflow/index.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/Delete.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/Rename.tsx
  ui/src/pages/namespace/Explorer/Workflow/Edit/WorkflowEditor.tsx
  ui/src/pages/namespace/Explorer/Workflow/components/RunWorkflow.tsx
  ui/src/pages/namespace/JqPlayground/index.tsx
  ui/src/pages/namespace/Mirror/Detail/index.tsx
  ui/src/pages/namespace/Permissions/Groups/Create.tsx
  ui/src/pages/namespace/Permissions/Groups/Delete.tsx
  ui/src/pages/namespace/Permissions/Groups/Edit.tsx
  ui/src/pages/namespace/Permissions/Policy/Editor.tsx
  ui/src/pages/namespace/Permissions/Tokens/Create/index.tsx
  ui/src/pages/namespace/Permissions/Tokens/Delete.tsx
  ui/src/pages/namespace/Services/List/Rebuild.tsx
  ui/test/utils.tsx
  ui/yarn.lock
Labels: ui, refactor

#1492 [DIR-1492] Fix flaky tests and auth token support in test utils
  ui/e2e/gateway/consumers/utils.ts
  ui/e2e/gateway/routes/utils.ts
  ui/e2e/services/utils.ts
  ui/e2e/utils/files.ts
Labels: ui, testing

#1434 [DIR-1069] new event history API
  openapi/src/openapi.yaml
  openapi/src/paths/events.yaml
  openapi/src/paths/paths.yaml
  pkg/flow/bytedata/data.go
  pkg/flow/db-events.go
  pkg/flow/engine.go
  pkg/flow/events.go
  pkg/flow/routing.go
  pkg/flow/server.go
  pkg/refactor/api/api.go
  pkg/refactor/api/events.go
  pkg/refactor/api/plattformlogs.go
  pkg/refactor/api/sse_helper.go
  pkg/refactor/cmd/main.go
  pkg/refactor/database/db_schema.sql
  pkg/refactor/datastore/datastore.go
  pkg/refactor/datastore/datastoresql/datastore.go
  pkg/refactor/datastore/datastoresql/eventstore.go
  pkg/refactor/datastore/datastoresql/eventstore_history.go
  pkg/refactor/datastore/datastoresql/eventstore_history_test.go
  pkg/refactor/datastore/datastoresql/eventstore_listener.go
  pkg/refactor/datastore/datastoresql/eventstore_listener_test.go
  pkg/refactor/datastore/datastoresql/eventstore_test.go
  pkg/refactor/datastore/datastoresql/eventstore_topic.go
  pkg/refactor/datastore/datastoresql/eventstore_topic_test.go
  pkg/refactor/datastore/datastoresql/staggingevents.go
  pkg/refactor/datastore/eventsstore.go
  pkg/refactor/events/events.go
  pkg/refactor/events/eventworker.go
  pkg/refactor/events/process.go
  pkg/refactor/events/process_test.go
  tests/events/events_v2.test.js
Labels: improvement, backend

#1500 [DIR-1510] Minor fixes
  pkg/flow/grpc-namespace-variables.go
  pkg/flow/grpc-workflow-variables.go
  pkg/flow/grpc/namespaces.pb.go
  pkg/flow/grpc/namespaces.proto
  pkg/flow/grpc/util.pb.go
  pkg/flow/grpc/util.proto
  pkg/flow/grpc/variables.pb.go
  pkg/flow/grpc/variables.proto
  tests/babel.config.js
  tests/gateway/target_flow.test.js
  tests/gateway/target_wf_var.test.js
  tests/jest.config.js
Labels: bug, backend

#1502 Minor Fixes: combine all ci jobs for backend, in a single workflow
  .github/workflows/backend_prebuild.yml
  .github/workflows/go-licenses.yml
  .github/workflows/go-lint.yml
  .github/workflows/go-unittests.yml
Labels: backend, refactor

#1503 Minor Fixes: combine all ci jobs for backend, in a single workflow
  .github/workflows/backend_prebuild.yml
  .github/workflows/ui_prebuild.yml
Labels: backend

#1496 [DIR-1491] Improve metrics
  ui/public/locales/en/translation.json
  ui/src/pages/namespace/Explorer/Workflow/Overview/Donut.tsx
  ui/src/pages/namespace/Explorer/Workflow/Overview/Metrics/Content.tsx
  ui/src/pages/namespace/Explorer/Workflow/Overview/Metrics/Donut.tsx
  ui/src/pages/namespace/Explorer/Workflow/Overview/Metrics/index.tsx
  ui/src/pages/namespace/Explorer/Workflow/Overview/Metrics/utils.tsx
Labels: improvement, ui

#1504 Minor Fix: add backed-build.yaml
  .github/workflows/backend-build.yml
  .github/workflows/backend-prebuild.yml
  .github/workflows/ui-playwright.yml
  .github/workflows/ui-prebuild.yml
  .github/workflows/ui-storybook.yml
Labels: backend, refactor

#1506 Minor Fix: Remove bananas from ci workflows
  .github/workflows/backend-build.yml
  .github/workflows/backend-prebuild.yml
  .github/workflows/ui-prebuild.yml
Labels: backend, refactor

#1508 Minor Fix: refactor all workflows into a single one
  .github/workflows/backend-prebuild.yml
  .github/workflows/build.yml
  .github/workflows/ui-prebuild.yml
Labels: backend

#1512 Minor Fix: e2e ci.
  .github/workflows/build.yml
Labels: bug, backend

#1514 [DIR-1517] Remove unused code
  .github/workflows/build.yml
  pkg/refactor/cmd/main.go
  pkg/refactor/core/gateway.go
  pkg/refactor/gateway/gateway.go
  pkg/refactor/gateway/gateway_test.go
Labels: backend, refactor

#1513 [DIR 1513] add missing resend a event API for v2
  openapi/src/paths/events.yaml
  openapi/src/paths/paths.yaml
  pkg/refactor/api/events.go
Labels: backend, refactor
