Repository direktiv/direktiv, pull requests merged in 2024-03, with the labels that each got.

#1340 [DIR-1346] remove-old-filesystem-api-tests
  .github/workflows/api-e2e.yml
  .github/workflows/k3s-e2e-tests.yml
  tests/filesystem/create_file.test.js
  tests/filesystem/create_workflow_file.test.js
  tests/filesystem/directory.test.js
  tests/filesystem/root.test.js
  tests/filesystem/update_file.test.js
  tests/filesystem/workflow.test.js
  tests/namespaces/basic_create.test.js
  tests/namespaces/basic_crud.test.js
  tests/namespaces/basic_delete.test.js
  tests/namespaces/basic_update.test.js
  tests/namespaces/lists.test.js
  tests/namespaces/logs.test.js
  tests/namespaces/namespace.test.js
  tests/namespaces/namespaces.test.js
  tests/namespaces/regex.test.js
  tests/namespaces/structure.test.js
Labels: backend, refactor

#1342 [DIR-1348] remove-old-filesystem-calls-from-variables-and-secrets-tests
  tests/functions/files.test.js
  tests/logparser/callpath.test.js
  tests/secrets/secrets_read.test.js
  tests/services/action_workflow_and_run.test.js
  tests/variables/instvars.test.js
  tests/variables/nsvars.test.js
  tests/variables/wfvars.test.js
Labels: backend, refactor

#1343 [DIR-1349] remove-old-filesystem-calls-from-gateway-tests
  tests/common/helpers.js
  tests/engine/simple-subflow.test.js
  tests/events/workflow_events.test.js
  tests/filesystem/read_directory_v2.test.js
  tests/functions/files.test.js
  tests/gateway/endpoints_crud.test.js
  tests/gateway/http_header_plugin.test.js
  tests/gateway/js_inbound.test.js
  tests/gateway/js_outbound.test.js
  tests/gateway/target_file.test.js
  tests/gateway/target_flow.test.js
  tests/gateway/target_ns_var.test.js
  tests/gateway/target_wf_var.test.js
  tests/kubernetes/function-patch.test.js
  tests/kubernetes/generic-container.test.js
  tests/kubernetes/special-command.test.js
  tests/logparser/callpath.test.js
  tests/services/env_variables.test.js
  tests/services/new_service_crud_and_run.test.js
  tests/services/parse_multiple_workflow_services.test.js
  tests/services/rename_delete_service.test.js
  tests/services/update_service.test.js
Labels: backend, refactor

#1344 [DIR-1350] remove-all-legacy-filesystem-helper-functions-in-test-code
  .github/workflows/k3s-e2e-tests.yml
  tests/common/helpers.js
  tests/filesystem/read_directory_v2.test.js
  tests/filesystem/update_file_path_v2.test.js
  tests/gateway/endpoints_crud.test.js
  tests/services/rename_delete_service.test.js
  tests/services/update_service.test.js
Labels: backend, refactor

#1345 [DIR-1351] fix-linter-issues
  .github/workflows/api-e2e.yml
  .github/workflows/k3s-e2e-tests.yml
  pkg/flow/server.go
  tests/.eslintrc
  tests/cli/cli.test.js
  tests/cli/mockdata/direktiv-project/.direktiv.yaml
  tests/cli/mockdata/direktiv-project/simplewf.yaml
  tests/cli/mockdata/direktiv-project/subfolder/simplewfInSubfolder.yaml
  tests/events/send_events.test.js
  tests/events/send_helper.js
  tests/events/workflow_events.test.js
  tests/events/workflow_events_and.test.js
  tests/events/workflow_events_or.test.js
  tests/kubernetes/function-patch.test.js
  tests/kubernetes/generic-container.test.js
  tests/kubernetes/special-command.test.js
  tests/mirror/mirror.test.js
  tests/mirror/namespaces_git_mirror.test.js
  tests/namespaces/basic_create.test.js
  tests/services/new_service_crud_and_run.test.js
Labels: backend, refactor

#1346 [DIR-1327] deleting-a-workflow-does-not-delete-a-event-listener
  pkg/flow/db-events.go
  pkg/flow/grpc-nodes.go
  pkg/flow/server.go
  pkg/refactor/api/filesystem.go
  pkg/refactor/pubsub/pubsub.go
Labels: bug, backend

#1347 [DIR-1352] Fix filesystem mime type setting
  pkg/flow/bytedata/data2.go
  pkg/flow/grpc-workflow.go
  pkg/refactor/gateway/gateway_test.go
  pkg/refactor/mirror/apply.go
  tests/mirror/mirror.test.js
Labels: bug, backend

#1348 [DIR-1275] Add variables api docs
  openapi/src/openapi.yaml
  openapi/src/paths/paths.yaml
  openapi/src/paths/variables.yaml
Labels: backend

#1349 Alan/e2e fixes
  .github/workflows/k3s-e2e-tests.yml
  tests/events/workflow_events.test.js
  tests/events/workflow_events_and.test.js
  tests/events/workflow_events_or.test.js
  tests/functions/files.test.js
  tests/services/parse_multiple_workflow_services.test.js
Labels: testing, backend, devops

#1337 [DIR-638] Improve 404 handling and show an error page when a requested resource does not exist.
  ui/e2e/explorer/index.spec.ts
  ui/public/locales/en/translation.json
  ui/src/api/files/query/file.ts
  ui/src/pages/namespace/Explorer/index.tsx
  ui/src/pages/namespace/Gateway/Routes/Table/Row/index.tsx
  ui/src/pages/namespace/Layout.tsx
  ui/src/util/router/ErrorPage.tsx
  ui/src/util/router/pages.tsx
Labels: improvement, ui

#1351 [DIR-1098] integrate fluentbit as our logging engine
  .github/workflows/charts.yml
  .github/workflows/k3s-e2e-tests.yml
  charts/direktiv/Chart.lock
  charts/direktiv/templates/flow/flow-secrets-fluentbit.yaml
  charts/direktiv/values.yaml
  openapi/src/openapi.yaml
  openapi/src/paths/paths.yaml
  openapi/src/paths/plattformlogs.yaml
  pkg/flow/database/recipient/recipient.go
  pkg/flow/engine.go
  pkg/flow/grpc-flow.go
  pkg/flow/grpc-internal.go
  pkg/flow/grpc-logs.go
  pkg/flow/memory.go
  pkg/flow/server.go
  pkg/refactor/api/api.go
  pkg/refactor/api/plattformlogs.go
  pkg/refactor/core/logentry.go
  pkg/refactor/database/db_schema.sql
  pkg/refactor/datastore/datastore.go
  pkg/refactor/datastore/datastoresql/datastore.go
  pkg/refactor/datastore/datastoresql/logstore_new.go
  pkg/refactor/datastore/namespaces.go
  pkg/refactor/datastore/plattformlogs.go
  pkg/refactor/engine/telemetry.go
  pkg/refactor/gateway/gateway.go
  pkg/refactor/gateway/plugins/auth/basic-auth.go
  pkg/refactor/gateway/plugins/auth/key-auth.go
  pkg/refactor/gateway/plugins/inbound/acl-plugin.go
  pkg/refactor/gateway/plugins/inbound/js-inbound.go
  pkg/refactor/gateway/plugins/outbound/js.go
  pkg/refactor/gateway/plugins/plugin.go
  pkg/refactor/gateway/plugins/target/target-ns-file.go
  pkg/refactor/gateway/plugins/target/target-ns-var.go
  pkg/refactor/gateway/plugins/target/target-workflow-var.go
  pkg/refactor/gateway/plugins/target/target-workflow.go
  tests/logs/basic_namespace_logs.test.js
Labels: feature, backend

#1355 [DIR-1359] playwrght simple implementation with make target
  .github/workflows/api-e2e.yml
  .github/workflows/ui-playwright.yml
  Makefile
  docker-compose.yaml
  ui/package.json
Labels: devops

#1356 [DIR-1360] Fix target make docker-e2e-playwright
  docker-compose.yaml
  ui/Dockerfile
  ui/package.json
Labels: bug

#1357 [DIR-1357] Fix apiv2 logtest
  .github/workflows/k3s-e2e-tests.yml
  charts/direktiv/values.yaml
  tests/common/retry.js
  tests/logs/basic_namespace_logs.test.js
Labels: bug, devops

#1353 [DIR-1356] Cleanup logs v2
  pkg/refactor/api/plattformlogs.go
Labels: backend, refactor

#1361 [DIR-1363] Clean unused go server in UI
  ui/deploy.nomad
  ui/frontend/go.mod
  ui/frontend/go.sum
  ui/frontend/main.go
  ui/frontend/server/config.go
  ui/frontend/server/error.go
  ui/frontend/server/route-manager.go
  ui/frontend/server/route.go
  ui/frontend/server/server.go
Labels: ui, refactor

#1363 [DIR-1253] Added Gitlab webhook plugin
  pkg/refactor/gateway/plugins/auth/gitlab-event.go
  pkg/refactor/gateway/plugins/auth/gitlab-event_test.go
  tests/gateway/gitlab_auth.test.js
Labels: feature, backend

#1366 [DIR-1334] Added atob and btoa to js scripting
  pkg/jqer/jqer.go
  tests/engine/base64js.test.js
Labels: improvement, backend

#1358 [DIR-1362] Update Direktiv version in charts
  charts/direktiv/Chart.yaml
Labels: devops

#1367 [DIR-1277] Updated Readme
  README.md
  assets/images/direktiv-logo-50.png
  assets/images/direktiv.gif
  assets/images/flow.png
Labels: devops

#1364 [DIR-1211] Add Slack webhook plugin
  go.mod
  go.sum
  pkg/refactor/gateway/plugins/auth/gitlab-event.go
  pkg/refactor/gateway/plugins/auth/slack-event.go
Labels: feature, backend

#1368 [DIR-1366] 1366 routine backend cleanup
  .golangci.yaml
  cmd/exec/cmd/events/events.go
  cmd/exec/cmd/workflows/workflows.go
  pkg/api/util.go
  pkg/flow/grpc-logs.go
  tests/gateway/gitlab_auth.test.js
  tests/logs/basic_namespace_logs.test.js
  tests/services/new_service_crud_and_run.test.js
Labels: refactor

#1369 [DIR-1367] Re-add fluent-bit to charts properly
  charts/direktiv/Chart.lock
  charts/direktiv/Chart.yaml
  charts/direktiv/charts/fluent-bit-0.43.0.tgz
Labels: bug, charts

#1370 [DIR-1368] Clean UI makefile and docker build
  Makefile
  charts/direktiv/templates/frontend/frontend-deployment.yaml
  ui/Dockerfile
  ui/Dockerfile.base
  ui/Dockerfile.prod
  ui/Dockerfile.prod.dockerignore
  ui/conf/entrypoint.sh
  ui/conf/nginx.dev.conf
  ui/conf/prod/entrypoint.sh
  ui/conf/prod/nginx.conf
  ui/nginx.nomad
Labels: backend, refactor

#1332 [DIR-1331][DIR-1332][DIR-1333] Add forms for additional auth plugins
  ui/public/locales/en/translation.json
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Auth/WebhookAuthForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Auth/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/utils.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/plugins/auth/githubWebhookAuth.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/plugins/auth/index.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/plugins/auth/schema.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/plugins/auth/webhookAuth.ts
Labels: ui, feature

#1360 [DIR-1078] update cli to use v2 logs apis
  cmd/exec/cmd/logs.go
  cmd/exec/cmd/root.go
  cmd/exec/cmd/workflows/workflows.go
Labels: cli, refactor

#1362 [DIR-1364] Fix SSE empty stream impl
  openapi/src/paths/paths.yaml
  openapi/src/paths/plattformlogs.yaml
  pkg/refactor/api/plattformlogs.go
  pkg/refactor/core/logentry.go
  pkg/refactor/datastore/datastoresql/logstore_new.go
  pkg/refactor/engine/telemetry.go
Labels: bug, backend

#1371 [DIR-1288] Improve yaml formatting (display multiline strings in block style)
  ui/e2e/explorer/consumer/utils.ts
  ui/e2e/explorer/route/index.spec.ts
  ui/e2e/explorer/route/utils.ts
  ui/e2e/explorer/service/index.spec.ts
  ui/e2e/explorer/service/utils.ts
  ui/e2e/services/utils.ts
  ui/package.json
  ui/src/design/WorkflowDiagram/index.tsx
  ui/src/index.d.ts
  ui/src/pages/namespace/Explorer/Workflow/components/utils.ts
  ui/src/pages/namespace/Explorer/utils.ts
  ui/yarn.lock
Labels: improvement, ui

#1372 [DIR-1067] Instances v2 api.
  .github/workflows/api-e2e.yml
  openapi/src/objects.yaml
  openapi/src/parameters.yaml
  openapi/src/paths/instances.yaml
  openapi/src/paths/paths.yaml
  pkg/api/flow.go
  pkg/flow/engine.go
  pkg/flow/grpc-instances.go
  pkg/flow/metrics.go
  pkg/flow/server.go
  pkg/flow/status.go
  pkg/refactor/api/api.go
  pkg/refactor/api/instances.go
  pkg/refactor/cmd/main.go
  pkg/refactor/core/app.go
  pkg/refactor/instancestore/instance.go
  pkg/refactor/instancestore/instance_test.go
  pkg/refactor/instancestore/instancestoresql/sql.go
  pkg/util/instance.go
  tests/engine/cancel.test.js
  tests/instances/blobs.test.js
  tests/instances/cancel.test.js
  tests/instances/wait-fail.test.js
  tests/instances/wait-success.test.js
  tests/logs/basic_namespace_logs.test.js
  ui/src/api/instances/schema.ts
  ui/src/design/Badge/index.tsx
  ui/src/pages/namespace/Instances/utils.ts
Labels: backend

#1374 [DIR-1365] remove dependencies to external cdn resources
  ui/package.json
  ui/src/design/Editor/index.tsx
  ui/src/design/Editor/theme-dark.ts
  ui/src/design/Editor/theme-light.ts
  ui/yarn.lock
Labels: improvement, ui

#1376 [DIR-1335] Repair the link to the Docs
  ui/src/pages/namespace/Explorer/Workflow/components/FormInputHint.tsx
Labels: bug, ui

#1377 [DIR-1379] event listeners error trailing junk after numeric literal at
  pkg/refactor/datastore/datastoresql/eventstore.go
  pkg/refactor/datastore/datastoresql/eventstore_test.go
Labels: bug, backend

#1378 [DIR-1382] Disable traced logging for now
  charts/direktiv/values.yaml
Labels: configuration, charts

#1354 [DIR-1292] Sync between JSON Input and Form Input
  ui/e2e/explorer/workflow/run.spec.ts
  ui/src/design/JSONschemaForm/index.tsx
  ui/src/pages/namespace/Explorer/Workflow/components/RunWorkflow.tsx
  ui/src/util/helpers.ts
Labels: bug, ui

#1383 Add secrets v2 openapi
  openapi/src/openapi.yaml
  openapi/src/paths/instances.yaml
  openapi/src/paths/paths.yaml
  openapi/src/paths/secrets.yaml
Labels: backend

#1385 [DIR-722] Fix console error in Input/Output panel on the instances page
  ui/src/pages/namespace/Instances/Detail/Main/InputOutput/Input.tsx
  ui/src/pages/namespace/Instances/Detail/Main/InputOutput/Output.tsx
Labels: bug, ui

#1390 [DIR-1393] fix log scrolling issue
  ui/src/pages/namespace/Instances/Detail/Main/Logs/Entry.tsx
  ui/src/pages/namespace/Monitoring/Logs/Entry.tsx
Labels: bug, ui

#1386 [DIR-1318] Keep encryption key in helm chart during update
  charts/direktiv/templates/flow/flow-secrets.yaml
Labels: devops

#1392 [DIR-1293] JSON Form Input - Fix for copy and pasting values behavior
  ui/e2e/explorer/workflow/run.spec.ts
  ui/src/pages/namespace/Explorer/Workflow/components/RunWorkflow.tsx
Labels: bug, ui

#1393 [DIR-1398] Fixed make target for UI build
  Makefile
Labels: devops

#1394 [DIR-1399] Fix UI build Makefile
  Makefile
Labels: devops

#1397 [DIR-1401] Update charts
  charts/direktiv/Chart.yaml
  charts/direktiv/values.yaml
Labels: devops
