Repository direktiv/direktiv, pull requests merged in 2024-02, with the labels that each got.

#1240 [DIR-1025] Instance shows finished in UI although not completed
  ui/src/pages/namespace/Instances/Detail/InstanceDetail.tsx
  ui/src/pages/namespace/Instances/Detail/Main/Diagram/index.tsx
  ui/src/pages/namespace/Instances/Detail/Main/Diagram/utils.ts
Labels: bug, ui

#1246 Fixed colon missing in Makefile for frontend
  ui/Makefile
Labels: devops

#1245 [DIR-1206] Fix install
  charts/direktiv/Chart.lock
  charts/direktiv/charts/ingress-nginx-4.4.0.tgz
  charts/direktiv/charts/ingress-nginx-4.9.0.tgz
  charts/direktiv/charts/prometheus-15.18.0.tgz
  charts/direktiv/charts/prometheus-25.8.2.tgz
  scripts/installer.sh
Labels: devops

#1247 [DIR-1192] make-target-to-preview-openapi-spec
  .gitignore
  Makefile
  openapi/Makefile
  openapi/package-lock.json
  openapi/package.json
  openapi/src/openapi.yaml
  openapi/src/paths/gateway.yaml
  openapi/src/paths/gw_routes.yaml
  openapi/src/paths/registries.yaml
  openapi/src/paths/services.yaml
Labels: devops

#1242 [DIR-1154] Implements revised v2 API 'version' endpoint.
  openapi/Makefile
  openapi/src/openapi.yaml
  openapi/src/paths/version.yaml
  pkg/refactor/api/api.go
  tests/api/version.test.js
Labels: backend

#1248 [DIR-1215] Enable missing api e2e tests.
  .github/workflows/api-e2e.yml
  .github/workflows/k3s-e2e-tests.yml
Labels: bug, backend

#1244 [DIR-1194] test consumer editor
  ui/e2e/explorer/consumer/index.spec.ts
  ui/e2e/explorer/consumer/utils.ts
  ui/src/pages/namespace/Explorer/Consumer/ConsumerEditor/Form/index.tsx
  ui/src/pages/namespace/Explorer/Consumer/ConsumerEditor/index.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/index.tsx
Labels: ui, testing

#1203 [DIR-1038] Variablepicker
  ui/public/locales/en/translation.json
  ui/src/api/tree/query/variables.ts
  ui/src/api/variables/query/useVariables.ts
  ui/src/components/NamespaceVariablepicker/VariablePickerError.tsx
  ui/src/components/NamespaceVariablepicker/index.tsx
  ui/src/components/WorkflowVariablepicker/VariablePickerError.tsx
  ui/src/components/WorkflowVariablepicker/index.tsx
  ui/src/design/VariablePicker/index.stories.tsx
  ui/src/design/VariablePicker/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/TargetFlowVarForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/TargetNamespaceVarForm.tsx
  ui/src/pages/namespace/Explorer/Workflow/Settings/Variables/Edit.tsx
  ui/src/pages/namespace/Explorer/Workflow/Settings/Variables/index.tsx
  ui/src/pages/namespace/Settings/Variables/Edit.tsx
  ui/src/pages/namespace/Settings/Variables/index.tsx
Labels: improvement, ui

#1234 [DIR-1094] ee token permission display
  ui/src/pages/namespace/Permissions/components/PermisionsSelector.tsx
  ui/src/pages/namespace/Permissions/components/PermisionsSelector/Row.tsx
  ui/src/pages/namespace/Permissions/components/PermisionsSelector/index.tsx
  ui/src/pages/namespace/Permissions/components/PermisionsSelector/utils.ts
Labels: improvement, ui

#1252 [DIR-1219] implement files tree read endpoint
  .golangci.yaml
  openapi/src/objects.yaml
  openapi/src/openapi.yaml
  openapi/src/paths/filesystem.yaml
  pkg/refactor/api/api.go
  pkg/refactor/api/errors.go
  pkg/refactor/api/filesystem.go
  pkg/refactor/filestore/file.go
  tests/common/helpers.js
  tests/filesystem/read_directory_v2.test.js
Labels: feature, backend

#1254 [DIR-1220] Add delete endpoint.
  openapi/src/paths/filesystem.yaml
  pkg/refactor/api/filesystem.go
  tests/filesystem/read_directory_v2.test.js
Labels: improvement, backend

#1250 [DIR 1213] event topics are not including the event context
  pkg/flow/db-events.go
  pkg/refactor/database/db_schema.sql
  pkg/refactor/datastore/datastoresql/eventstore.go
  pkg/refactor/datastore/datastoresql/eventstore_test.go
  pkg/refactor/events/events.go
  tests/events/workflow_events.test.js
Labels: bug, backend

#1219 [DIR-1123] Add log prints using slog in the proper structure
  .golangci.yaml
  openapi/src/objects.yaml
  openapi/src/openapi.yaml
  openapi/src/paths/filesystem.yaml
  pkg/flow/engine.go
  pkg/flow/events.go
  pkg/flow/memory.go
  pkg/flow/scheduling.go
  pkg/flow/status.go
  pkg/refactor/api/api.go
  pkg/refactor/api/errors.go
  pkg/refactor/api/filesystem.go
  pkg/refactor/engine/telemetry.go
  pkg/refactor/filestore/file.go
  tests/common/helpers.js
  tests/filesystem/read_directory_v2.test.js
  ui/e2e/explorer/consumer/index.spec.ts
  ui/e2e/explorer/consumer/utils.ts
  ui/public/locales/en/translation.json
  ui/src/api/tree/query/variables.ts
  ui/src/api/variables/query/useVariables.ts
  ui/src/components/NamespaceVariablepicker/VariablePickerError.tsx
  ui/src/components/NamespaceVariablepicker/index.tsx
  ui/src/components/WorkflowVariablepicker/VariablePickerError.tsx
  ui/src/components/WorkflowVariablepicker/index.tsx
  ui/src/design/VariablePicker/index.stories.tsx
  ui/src/design/VariablePicker/index.tsx
  ui/src/pages/namespace/Explorer/Consumer/ConsumerEditor/Form/index.tsx
  ui/src/pages/namespace/Explorer/Consumer/ConsumerEditor/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/TargetFlowVarForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/TargetNamespaceVarForm.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/index.tsx
  ui/src/pages/namespace/Explorer/Workflow/Settings/Variables/Edit.tsx
  ui/src/pages/namespace/Explorer/Workflow/Settings/Variables/index.tsx
  ui/src/pages/namespace/Permissions/components/PermisionsSelector.tsx
  ui/src/pages/namespace/Permissions/components/PermisionsSelector/Row.tsx
  ui/src/pages/namespace/Permissions/components/PermisionsSelector/index.tsx
  ui/src/pages/namespace/Permissions/components/PermisionsSelector/utils.ts
  ui/src/pages/namespace/Settings/Variables/Edit.tsx
  ui/src/pages/namespace/Settings/Variables/index.tsx
Labels: improvement, backend

#1257 [DIR-1225] add create files endpoints
  openapi/src/paths/filesystem.yaml
  pkg/refactor/api/errors.go
  pkg/refactor/api/filesystem.go
  pkg/refactor/filestore/filestoresql/root_query.go
  tests/common/helpers.js
  tests/filesystem/create_file_v2.test.js
  tests/mirror/mirror.test.js
Labels: improvement, backend

#1249 [DIR-1114] Add fluentbit helm dependency
  .github/workflows/charts.yml
  .github/workflows/k3s-e2e-tests.yml
  charts/direktiv/Chart.lock
  charts/direktiv/Chart.yaml
  charts/direktiv/charts/fluent-bit-0.43.0.tgz
  charts/direktiv/templates/flow/flow-secrets-fluentbit.yaml
  charts/direktiv/values.yaml
  scripts/build/docker/all/docker/Dockerfile
  scripts/build/docker/all/multipass/install.sh
  scripts/installer.sh
Labels: charts

#1259 [DIR-1226] fix-filesystem-size
  pkg/refactor/filestore/file.go
  pkg/refactor/filestore/filestoresql/filestore.go
  pkg/refactor/filestore/filestoresql/root_query.go
  tests/filesystem/create_file_v2.test.js
Labels: bug, backend

#1260 [DIR-1227] bugfix-filestore-listdirektivfileswithdata
  pkg/refactor/cmd/main.go
  pkg/refactor/filestore/filestore.go
  pkg/refactor/filestore/filestoresql/root_query.go
  pkg/refactor/gateway/gateway.go
Labels: bug, backend

#1262 [DIR-1231] add validation to create endpoints
  pkg/refactor/api/filesystem.go
  tests/common/helpers.js
  tests/filesystem/create_file_v2.test.js
  tests/filesystem/trailing_slash.test.js
  tests/filesystem/validation_v2.test.js
Labels: feature, backend

#1253 [DIR-1097] sort the namespaces in the drop down
  ui/e2e/settings/deleteNamespace.spec.ts
  ui/src/api/namespaces/query/get.ts
Labels: improvement, ui

#1264 [DIR-1234] implement files tree update endpoint
  openapi/src/paths/filesystem.yaml
  pkg/refactor/api/filesystem.go
  tests/common/helpers.js
  tests/filesystem/create_file_v2.test.js
  tests/filesystem/trailing_slash.test.js
  tests/filesystem/update_file_path_v2.test.js
  tests/filesystem/update_file_v2.test.js
  tests/filesystem/validation_v2.test.js
Labels: feature, backend

#1265 [DIR-1236] cleanup grpc protocol file
  pkg/flow/grpc/protocol.proto
Labels: backend, refactor

#1255 [DIR-1190] Added environment variables to special command
  cmd/cmd-exec/pkg/commands/commands.go
  cmd/cmd-exec/pkg/commands/commands_test.go
  cmd/cmd-exec/pkg/server/server.go
  cmd/dinit/main.go
  cmd/direktiv/main.go
  tests/kubernetes/special-command.test.js
Labels: improvement, backend

#1266 [DIR-1151] variables get flushed when a workflow is renamed via
  pkg/refactor/api/filesystem.go
  pkg/refactor/core/runtime_variables.go
  pkg/refactor/datastore/datastoresql/runtime_variables.go
Labels: backend, refactor

#1269 [DIR-1242] Clean test code.
  tests/common/helpers.js
  tests/filesystem/create_file_v2.test.js
  tests/filesystem/read_directory_v2.test.js
  tests/filesystem/trailing_slash.test.js
  tests/filesystem/trailing_slash_v2.test.js
  tests/filesystem/update_file_path_v2.test.js
  tests/filesystem/update_file_v2.test.js
  tests/filesystem/validation_v2.test.js
Labels: backend, refactor

#1267 [DIR-1239] Fixed header and query access
  pkg/refactor/gateway/plugins/inbound/js-inbound.go
  pkg/refactor/gateway/plugins/inbound/js-inbound_test.go
  pkg/refactor/gateway/plugins/outbound/js.go
  pkg/refactor/gateway/plugins/outbound/js_test.go
  tests/gateway/js_inbound.test.js
  tests/gateway/js_outbound.test.js
Labels: bug, gateway

#1261 [DIR-1196] E2E Tests for Consumer Page
  ui/e2e/gateway/consumers/index.spec.ts
  ui/e2e/gateway/consumers/utils.ts
  ui/public/locales/en/translation.json
  ui/src/components/Breadcrumb/Gateway/Consumer.tsx
  ui/src/pages/namespace/Gateway/Consumers/Table/Row/index.tsx
  ui/src/pages/namespace/Gateway/Consumers/Table/index.tsx
  ui/src/pages/namespace/Gateway/Consumers/index.tsx
Labels: ui, testing

#1270 [DIR-1221] Changed header manipulation plugin to name/value pairs
  pkg/refactor/gateway/plugins/inbound/header_manipulation.go
  pkg/refactor/gateway/plugins/inbound/header_manipulation_test.go
  tests/gateway/http_header_plugin.test.js
Labels: gateway, refactor

#1271 [DIR-1243] Set default content type for flow target plugin
  pkg/refactor/gateway/plugins/target/target-workflow.go
  tests/gateway/target_flow.test.js
Labels: improvement, gateway

#1272 [DIR-1244] Add eslint setup to e2e code
  tests/.eslintrc
  tests/common/config.js
  tests/common/filesystem.js
  tests/common/helpers.js
  tests/common/index.js
  tests/common/regex.js
  tests/common/structs.js
  tests/common/utils.js
  tests/filesystem/create_file.test.js
  tests/filesystem/create_file_v2.test.js
  tests/filesystem/create_workflow_file.test.js
  tests/filesystem/directory.test.js
  tests/filesystem/read_directory_v2.test.js
  tests/filesystem/root.test.js
  tests/filesystem/trailing_slash_v2.test.js
  tests/filesystem/update_file.test.js
  tests/filesystem/update_file_path_v2.test.js
  tests/filesystem/update_file_v2.test.js
  tests/filesystem/validation_v2.test.js
  tests/filesystem/workflow.test.js
  tests/package-lock.json
  tests/package.json
Labels: backend, refactor

#1274 [DIR-1245] Maintain linter setting
  .golangci.yaml
  pkg/refactor/api/api.go
  pkg/refactor/api/filesystem.go
  pkg/refactor/core/service.go
  pkg/refactor/filestore/file.go
  pkg/refactor/mirror/manager.go
  pkg/refactor/service/manager.go
Labels: backend, refactor

#1273 [DIR-1233] Added custom logo to helm chart
  charts/direktiv/templates/frontend/frontend-config.yaml
  charts/direktiv/templates/frontend/frontend-deployment.yaml
  charts/direktiv/templates/frontend/frontend-logo.yaml
  charts/direktiv/values.yaml
Labels: improvement, charts

#1268 [DIR-1128] fix bug with utf 8 special characters
  ui/e2e/explorer/workflow/run.spec.ts
  ui/e2e/explorer/workflow/utils.ts
  ui/package.json
  ui/src/api/jq/mutate/executeQuery.ts
  ui/src/pages/namespace/Events/History/ViewEvent.tsx
  ui/src/pages/namespace/Explorer/Consumer/ConsumerEditor/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/index.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/index.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/FileViewer.tsx
  ui/src/pages/namespace/Explorer/Workflow/Edit/WorkflowEditor.tsx
  ui/src/pages/namespace/Explorer/Workflow/components/RunWorkflow.tsx
  ui/src/pages/namespace/Instances/Detail/Main/Diagram/index.tsx
  ui/src/pages/namespace/Instances/Detail/Main/InputOutput/Input.tsx
  ui/src/pages/namespace/Instances/Detail/Main/InputOutput/Output.tsx
  ui/yarn.lock
Labels: bug, ui

#1275 [DIR-1135] Load plugins in flow only
  .github/workflows/go-unittests.yml
  pkg/refactor/gateway/plugins/plugin.go
Labels: improvement, backend

#1277 [DIR-1214] switch to version v2 api
  ui/e2e/errorPage.spec.ts
  ui/src/api/version/query/get.ts
  ui/src/api/version/schema.ts
  ui/src/pages/namespace/Layout.tsx
Labels: ui, refactor

#1278 [DIR-1207] Changed stop behaviour for "error" attribute for special command
  cmd/cmd-exec/pkg/commands/commands.go
  cmd/cmd-exec/pkg/server/server.go
Labels: improvement, backend

#1280 [DIR-1200] services-are-not-deleted
  pkg/refactor/service/knative_client.go
Labels: bug, backend

#1281 [DIR-1104] Create db migration document.
  pkg/refactor/database/db_schema.sql
  specification/db_migration.md
Labels: backend

#1282 [DIR-1145] Modified Javascript plugin to access consumer and URL parameters
  pkg/refactor/gateway/plugins/inbound/js-inbound.go
  pkg/refactor/gateway/plugins/inbound/js-inbound_test.go
  pkg/refactor/gateway/plugins/plugin.go
  tests/gateway/js_inbound.test.js
Labels: improvement, gateway

#1283 [DIR-1195] Added Tests for Gateway Routes
  ui/e2e/gateway/routes/index.spec.ts
  ui/e2e/gateway/routes/utils.ts
  ui/src/components/Breadcrumb/Gateway/Routes.tsx
  ui/src/pages/namespace/Gateway/Routes/Table/index.tsx
Labels: ui, testing

#1285 [DIR-1266] Fixed colon issue in server-prod target
  ui/Makefile
Labels: devops

#1256 [DIR-1216] [DIR-1251] add header-manipulation plugin to the UI
  ui/e2e/explorer/service/index.spec.ts
  ui/public/locales/en/translation.json
  ui/src/components/Form/Array/ArrayItem.tsx
  ui/src/components/Form/Array/index.tsx
  ui/src/components/Form/Array/types.ts
  ui/src/components/Form/ArrayInput.tsx
  ui/src/pages/namespace/Explorer/Consumer/ConsumerEditor/Form/TagsGroupsArrayForm.tsx
  ui/src/pages/namespace/Explorer/Consumer/ConsumerEditor/Form/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Inbound/AclForm/AclArrayForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Inbound/AclForm/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Inbound/HeaderManipulationForm/HeaderArrayForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Inbound/HeaderManipulationForm/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Inbound/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/utils.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/plugins/inbound/headerManipulation.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/plugins/inbound/index.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/plugins/inbound/schema.ts
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/Form/Envs/EnvItemForm.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/Form/Envs/index.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/Form/EnvsArrayForm.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/Form/index.tsx
Labels: ui, feature

#1290 [DIR-1264] Bugfix: publish pubsub events in filesystem apiv2
  pkg/refactor/api/api.go
  pkg/refactor/api/filesystem.go
  pkg/refactor/cmd/main.go
  pkg/refactor/core/app.go
Labels: bug, backend

#1288 [DIR-1131] slog for flow
  .github/workflows/charts.yml
  .github/workflows/k3s-e2e-tests.yml
  charts/direktiv/Chart.lock
  charts/direktiv/Chart.yaml
  charts/direktiv/charts/fluent-bit-0.43.0.tgz
  charts/direktiv/templates/flow/flow-secrets-fluentbit.yaml
  charts/direktiv/values.yaml
  pkg/flow/engine.go
  pkg/flow/events.go
  pkg/flow/memory.go
  pkg/flow/scheduling.go
  pkg/flow/status.go
  pkg/refactor/engine/telemetry.go
  scripts/build/docker/all/docker/Dockerfile
  scripts/build/docker/all/multipass/install.sh
  scripts/installer.sh
Labels: backend, refactor

#1296 DIR-1289] remove-namespace-config-and-namespace-renaming-feature
  cmd/flow/main.go
  cmd/flow/namespace.go
  pkg/api/flow.go
  pkg/api/routes.go
  pkg/flow/broadcast.go
  pkg/flow/config.go
  pkg/flow/engine.go
  pkg/flow/grpc-mirror.go
  pkg/flow/grpc-namespaces.go
  pkg/flow/grpc/internal.pb.go
  pkg/flow/grpc/internal.proto
  pkg/flow/grpc/namespaces.pb.go
  pkg/flow/grpc/namespaces.proto
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
  pkg/refactor/core/namespaces.go
  pkg/refactor/database/db_schema.sql
  pkg/refactor/datastore/datastoresql/namespaces.go
  pkg/refactor/engine/settings.go
Labels: backend, refactor

#1297 [DIR-1290] remove unused grpc endpoints
  pkg/api/server.go
  pkg/flow/flow.go
  pkg/flow/grpc-workflow.go
  pkg/flow/grpc/build.pb.go
  pkg/flow/grpc/build.proto
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
Labels: backend, refactor

#1298 [DIR-1291] prepare apiv2 skeleton
  pkg/refactor/api/api.go
  pkg/refactor/api/mirrors.go
  pkg/refactor/api/namespaces.go
  pkg/refactor/api/secrets.go
Labels: backend, refactor

#1299 [DIR-1291] Implement pesudo namespace api v2
  pkg/refactor/api/api.go
  pkg/refactor/api/mirrors.go
  pkg/refactor/api/namespaces.go
  pkg/refactor/core/namespaces.go
  pkg/refactor/database/database.go
  pkg/refactor/datastore/datastoresql/mirror.go
  pkg/refactor/mirror/store.go
Labels: backend

#1301 [DIR-1297] refactor move secrets to datastore package
  pkg/flow/bytedata/data2.go
  pkg/flow/grpc-secrets.go
  pkg/flow/secrets.go
  pkg/refactor/api/errors.go
  pkg/refactor/api/secrets.go
  pkg/refactor/datastore/datastore.go
  pkg/refactor/datastore/datastoresql/datastore.go
  pkg/refactor/datastore/datastoresql/secrets.go
  pkg/refactor/datastore/datastoresql/secrets_test.go
  pkg/refactor/datastore/secrets.go
Labels: backend, refactor

#1286 [DIR-1262] Implement mirror logs
  pkg/flow/server.go
  pkg/refactor/mirror/apply.go
  pkg/refactor/mirror/callbacks.go
  pkg/refactor/mirror/manager.go
  pkg/refactor/mirror/mirror_test.go
  pkg/refactor/mirror/parser.go
  pkg/refactor/mirror/parser_test.go
Labels: improvement, backend

#1304 [DIR-1303] Test listing variable and secrets
  pkg/refactor/api/variables.go
  pkg/refactor/datastore/runtime_variables.go
  tests/secrets2/basic_create.test.js
  tests/secrets2/basic_crud.test.js
  tests/secrets2/basic_delete.test.js
  tests/secrets2/basic_update.test.js
  tests/secrets2/structure.test.js
  tests/variables2/basic_create.test.js
  tests/variables2/basic_crud.test.js
  tests/variables2/basic_delete.test.js
  tests/variables2/basic_update.test.js
  tests/variables2/structure.test.js
Labels: backend

#1308 [DIR-1307] bug fix namespace api v2 doesnt do updates
  pkg/refactor/api/namespaces.go
  pkg/refactor/datastore/datastoresql/mirror.go
  tests/namespaces2/basic_crud.test.js
  tests/namespaces2/basic_update.test.js
  tests/namespaces2/structure.test.js
Labels: bug, backend

#1307 Remove dead code
  pkg/flow/events.go
  pkg/flow/scheduling.go
  pkg/flow/server.go
  pkg/flow/timers.go
Labels: refactor

#1311 [DIR-1302] improve v2 filesystem api semantics
  openapi/src/openapi.yaml
  openapi/src/paths/filesystem.yaml
  pkg/refactor/api/api.go
  pkg/refactor/api/filesystem.go
  pkg/refactor/filestore/filestoresql/root_query.go
  tests/common/helpers.js
  tests/filesystem/create_file_v2.test.js
  tests/filesystem/read_directory_v2.test.js
  tests/filesystem/update_file_v2.test.js
  tests/filesystem/validation_v2.test.js
Labels: backend

#1312 [DIR-1309] clean up service logic
  pkg/model/resources.go
  pkg/refactor/cmd/main.go
  pkg/refactor/core/service.go
  pkg/refactor/mirror/parser.go
  pkg/refactor/service/client.go
  pkg/refactor/service/docker_client.go
  pkg/refactor/service/helper.go
  pkg/refactor/service/knative_client.go
  pkg/refactor/service/manager.go
  pkg/refactor/service/service.go
  pkg/refactor/spec/service.go
Labels: backend, refactor

#1313 [DIR-1310] move reconcile logic to a seprate package
  pkg/refactor/reconcile/reconcile.go
  pkg/refactor/reconcile/reconcile_test.go
  pkg/refactor/service/client.go
  pkg/refactor/service/manager.go
Labels: backend, refactor

#1318 [DIR-1316] Updating Translation File
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/Form/index.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/schema.ts
Labels: ui, refactor

#1316 [DIR-1188] Deletion of redundant code
  ui/src/design/Command/index.tsx
  ui/src/design/ContextMenu/index.tsx
  ui/src/design/Dropdown/index.tsx
  ui/src/design/Filepicker/index.tsx
  ui/src/design/Notification/index.tsx
  ui/src/design/Select/index.tsx
  ui/src/design/VariablePicker/index.tsx
Labels: ui, refactor

#1319 [DIR-1317] Context fix for running instances
  pkg/flow/engine.go
  pkg/flow/memory.go
  pkg/flow/metrics.go
  pkg/flow/scheduling.go
  pkg/flow/status.go
Labels: bug, backend

#1310 [DIR-1208] Display scaling note for services
  ui/public/locales/en/translation.json
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/Form/index.tsx
  ui/src/pages/namespace/Services/Detail/Header.tsx
  ui/src/pages/namespace/Services/Detail/Scale.tsx
Labels: improvement, ui

#1291 [DIR-1281] Add release.yaml for auto-generating release notes
  .github/release.yml
  .github/workflows/charts.yml
  Dockerfile
  charts/direktiv/Chart.yaml
  charts/direktiv/templates/frontend/frontend-deployment.yaml
  pkg/flow/engine.go
  pkg/flow/grpc-mirror.go
  pkg/flow/locks.go
  pkg/flow/memory.go
  pkg/flow/metrics.go
  pkg/flow/scheduling.go
  pkg/flow/status.go
  pkg/refactor/datastore/datastoresql/logstore.go
  ui/Dockerfile.prod
Labels: devops

#1284 [DIR-1193] Add gateway editor e2e test
  ui/e2e/explorer/route/index.spec.ts
  ui/e2e/explorer/route/utils.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Inbound/AclForm/AclArrayForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/utils.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/index.ts
  ui/src/pages/namespace/Explorer/utils.ts
Labels: ui, testing

#1330 [DIR-1267] Fix e2e Service tests on v2 API
  ui/e2e/instances/list/index.spec.ts
  ui/e2e/services/details.spec.ts
  ui/e2e/services/list.spec.ts
  ui/e2e/services/utils.ts
  ui/e2e/utils/files.ts
Labels: ui, testing

#1333 [DIR-1280] Removed README badges
  README.md
Labels: devops

#1335 [DIR-1339] Revert [DIR-1119][DIR-1098] [DIR-1076][DIR-1114] fluent-bit integration #1288
  .github/workflows/charts.yml
  .github/workflows/k3s-e2e-tests.yml
  charts/direktiv/Chart.lock
  charts/direktiv/Chart.yaml
  charts/direktiv/templates/flow/flow-secrets-fluentbit.yaml
  charts/direktiv/values.yaml
  pkg/flow/engine.go
  pkg/flow/events.go
  pkg/flow/memory.go
  pkg/flow/scheduling.go
  pkg/flow/status.go
  pkg/refactor/engine/telemetry.go
Labels: backend, refactor

#1334 [DIR-1313] Remove postgres locks from the engine.
  pkg/api/flow.go
  pkg/api/server.go
  pkg/flow/cancel.go
  pkg/flow/db-events.go
  pkg/flow/engine.go
  pkg/flow/eventing.go
  pkg/flow/events.go
  pkg/flow/grpc-files.go
  pkg/flow/grpc-flow.go
  pkg/flow/grpc-instances.go
  pkg/flow/grpc-internal.go
  pkg/flow/grpc-logs.go
  pkg/flow/grpc-mirror.go
  pkg/flow/grpc-namespaces.go
  pkg/flow/grpc-nodes.go
  pkg/flow/grpc-workflow.go
  pkg/flow/instance_messages.go
  pkg/flow/locks.go
  pkg/flow/memory.go
  pkg/flow/metrics.go
  pkg/flow/pagination.go
  pkg/flow/routing.go
  pkg/flow/scheduling.go
  pkg/flow/server.go
  pkg/flow/states/validation.go
  pkg/flow/status.go
  pkg/flow/temporary.go
  pkg/flow/timers.go
  pkg/flow/trace.go
  pkg/refactor/database/db_schema.sql
  pkg/refactor/engine/messages.go
  pkg/refactor/gateway/gateway.go
  pkg/refactor/instancestore/instance.go
  pkg/refactor/instancestore/instance_data_query_test.go
  pkg/refactor/instancestore/instance_test.go
  pkg/refactor/instancestore/instancestoresql/instance_data_query.go
  pkg/refactor/instancestore/instancestoresql/instancestoresql_test.go
  pkg/refactor/instancestore/instancestoresql/sql.go
  pkg/refactor/instancestore/instancestoresql/sql_builders.go
  pkg/refactor/instancestore/instancestoresql/sql_builders_test.go
  specification/db_migration.md
  tests/events/workflow_events.test.js
  tests/events/workflow_events_and.test.js
  tests/events/workflow_events_or.test.js
  tests/kubernetes/special-command.test.js
  tests/namespaces/logs.test.js
  tests/services/git_mirror_with_services.test.js
  tests/services/new_service_crud_and_run.test.js
  tests/variables2/basic_crud.test.js
Labels: improvement, backend
