Repository direktiv/direktiv, pull requests merged in 2024-12, with the labels that each got.

#1713 [DIR-1803] move dinit into dirketiv binary
  cmd/dinit/main.go
  cmd/direktiv/flow.go
  cmd/direktiv/main.go
  pkg/gateway/router.go
  pkg/service/helper.go
Labels: backend

#1714 house keeping
  charts/direktiv/templates/flow/flow-deployment.yaml
  cmd/cmd-exec/README.md
  cmd/direktiv/flow.go
  docker-compose.yaml
  pkg/gateway/plugins.go
  pkg/service/helper.go
Labels: refactor

#1715 [DIR-1822] Integrate opensearch
  .github/workflows/charts.yml
  charts/direktiv/Chart.lock
  charts/direktiv/Chart.yaml
  charts/direktiv/charts/opensearch-2.27.1.tgz
  charts/direktiv/templates/flow/flow-deployment.yaml
  charts/direktiv/values.yaml
  go.mod
  go.sum
  pkg/core/app.go
  pkg/flow/server.go
Labels: charts, devops

#1716 [DIR-1805] kind setup
  .gitignore
  Makefile
  charts/direktiv/Chart.lock
  charts/direktiv/templates/flow/flow-deployment.yaml
  charts/direktiv/values.yaml
  kind-config-cluster.yaml
  kind-config.yaml
  kind/deploy-ingress-nginx.yaml
  kind/knative-a-serving-operator.yaml
  kind/knative-b-serving-ns.yaml
  kind/knative-c-serving-basic.yaml
  kind/knative-d-serving-countour.yaml
  kind/knative-e-serving-ns-delete.yaml
  kind/postgres.yaml
  kind/svc-configmap.yaml
  make_cluster.mk
  make_k3s.mk
  make_tests.mk
  scripts/README.md
Labels: devops

#1725 [DIR-1850] - Implement test case for OpenAPI document renderer
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/design/RapiDoc/example.json
  ui/src/design/RapiDoc/index.stories.tsx
  ui/src/design/RapiDoc/index.tsx
  ui/src/design/RapiDoc/styles/RapiDoc.css
  ui/src/design/RapiDoc/types.d.ts
Labels: ui

#1731 [DIR-1727] Sort Direktiv secrets alphabetically
  ui/e2e/settings/index.spec.ts
  ui/src/api/secrets/query/get.ts
Labels: ui

#1733 [DIR-1807] - Add ability to select and delete multiple workflow variables
  ui/e2e/explorer/workflow/variables.spec.ts
  ui/src/api/variables/mutate/delete.ts
  ui/src/assets/locales/en/translation.json
  ui/src/pages/namespace/Explorer/Workflow/Settings/Variables/index.tsx
  ui/src/pages/namespace/Settings/Variables/Delete.tsx
  ui/src/pages/namespace/Settings/Variables/index.tsx
  ui/src/pages/namespace/Settings/components/ItemRow.tsx
Labels: ui

#1736 [DIR-1893] Re-enables instancestore test and fixes bugs within it.
  pkg/instancestore/instance_test.go
Labels: bug, testing, backend
