Repository direktiv/direktiv, pull requests merged in 2024-07, with the labels that each got.

#1688 [DIR-1698] Link only to instance from instances list
  ui/e2e/instances/list/index.spec.ts
  ui/src/assets/locales/en/translation.json
  ui/src/pages/namespace/Instances/List/Row.tsx
  ui/src/pages/namespace/Monitoring/Instances/Row.tsx
Labels: improvement, ui

#1682 [Dir-1675] Improvements in the file browser search
  ui/src/assets/locales/en/translation.json
  ui/src/pages/namespace/Explorer/Tree/EmptyDirectory.tsx
  ui/src/pages/namespace/Explorer/Tree/LevelUpNavigation.tsx
  ui/src/pages/namespace/Explorer/Tree/NoSearchResult.tsx
  ui/src/pages/namespace/Explorer/Tree/SearchBar.tsx
  ui/src/pages/namespace/Explorer/Tree/index.tsx
Labels: improvement, ui

#1687 [DIR-1661] Fix mirror log-list order
  pkg/datastore/datastoresql/mirror.go
  tests/part1/registry/multiple_namespaces.test.js
  tests/part1/registry/registry_crud_and_run.test.js
Labels: bug, backend

#1690 [DIR-1458] Fix test timing issue
  tests/events/workflow_events_or.test.js
Labels: testing, backend

#1691 [DIR-1701] Fix test-case
  tests/kubernetes/generic-container.test.js
Labels: testing, backend

#1689 [DIR-1660] Bugfix: implement namespaces array in target event plugin form
  ui/e2e/instances/details/header.spec.ts
  ui/package.json
  ui/src/components/Breadcrumb/Gateway/Routes.tsx
  ui/src/components/Breadcrumb/NamespaceSelector.tsx
  ui/src/components/NamespaceSelectorList/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/TargetEventForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/TargetFlowForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/TargetFlowVarForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/TargetNamespaceFileForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/TargetNamespaceVarForm.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/components/NamespaceSelectorListHandler.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/utils/useIsSystemNamespace.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/plugins/target/targetEvent.ts
  ui/src/pages/namespace/Gateway/Routes/Detail/Header.tsx
  ui/src/pages/namespace/Instances/Detail/Header/index.tsx
  ui/src/pages/namespace/Permissions/components/PermisionsSelector/index.tsx
  ui/yarn.lock
Labels: bug, ui

#1693 [DIR-1684] Fix server shutdown on bad service state
  pkg/core/service.go
  pkg/service/manager.go
Labels: bug, backend

#1692 [DIR-1714] Adds some sorting.
  pkg/api/instances.go
  pkg/api/sse_helper.go
  pkg/core/registry.go
  pkg/datastore/datastoresql/eventstore_history.go
  pkg/datastore/datastoresql/eventstore_topic.go
  pkg/datastore/datastoresql/mirror.go
  pkg/datastore/datastoresql/namespaces.go
  pkg/datastore/datastoresql/runtime_variables.go
  pkg/datastore/datastoresql/secrets.go
  pkg/datastore/mirror_test.go
  pkg/filestore/filestoresql/root_query.go
  pkg/registry/registry.go
  pkg/service/knative_client.go
  tests/part1/registry/multiple_namespaces.test.js
  tests/part1/registry/registry_crud_and_run.test.js
  tests/part1/secrets/basic_crud.test.js
  tests/part2/namespaces/basic_crud.test.js
  tests/part2/variables/basic_crud.test.js
  tests/part2/variables/list_wih_filters.test.js
Labels: bug, backend

#1670 [DIR-1645] Add UI support for creating typescript-workflows
  ui/.env.example
  ui/e2e/events/listeners.spec.ts
  ui/e2e/events/utils.ts
  ui/e2e/explorer/route/index.spec.ts
  ui/e2e/explorer/service/utils.ts
  ui/e2e/explorer/workflow/diagramEditor.spec.ts
  ui/e2e/explorer/workflow/run.spec.ts
  ui/e2e/explorer/workflow/settings.spec.ts
  ui/e2e/gateway/consumers/index.spec.ts
  ui/e2e/gateway/routes/details/index.spec.ts
  ui/e2e/gateway/routes/list/index.spec.ts
  ui/e2e/instances/details/diagram.spec.ts
  ui/e2e/instances/details/header.spec.ts
  ui/e2e/instances/details/inputOutput.spec.ts
  ui/e2e/instances/details/logs.spec.ts
  ui/e2e/instances/filter/index.spec.ts
  ui/e2e/instances/list/index.spec.ts
  ui/e2e/notificationmenu/index.spec.ts
  ui/e2e/services/details.spec.ts
  ui/e2e/services/list.spec.ts
  ui/e2e/utils/files.ts
  ui/e2e/utils/workflow.ts
  ui/src/api/files/schema.ts
  ui/src/assets/locales/en/translation.json
  ui/src/config/env/schema.ts
  ui/src/hooks/useTsWorkflowLibs.ts
  ui/src/pages/namespace/Explorer/Tree/__tests__/utils.test.ts
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Workflow/index.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Workflow/templates.tsx
  ui/src/pages/namespace/Explorer/Tree/utils.ts
  ui/src/pages/namespace/Explorer/Workflow/Edit/WorkflowEditor.tsx
Labels: ui, feature

#1655 [DIR-1644] UI support for typescript-workflows
  ui/.env.example
  ui/e2e/events/listeners.spec.ts
  ui/e2e/events/utils.ts
  ui/e2e/explorer/route/index.spec.ts
  ui/e2e/explorer/service/utils.ts
  ui/e2e/explorer/workflow/codeEditor.spec.ts
  ui/e2e/explorer/workflow/diagramEditor.spec.ts
  ui/e2e/explorer/workflow/run.spec.ts
  ui/e2e/explorer/workflow/settings.spec.ts
  ui/e2e/gateway/consumers/index.spec.ts
  ui/e2e/gateway/routes/details/index.spec.ts
  ui/e2e/gateway/routes/list/index.spec.ts
  ui/e2e/instances/details/diagram.spec.ts
  ui/e2e/instances/details/header.spec.ts
  ui/e2e/instances/details/inputOutput.spec.ts
  ui/e2e/instances/details/logs.spec.ts
  ui/e2e/instances/filter/index.spec.ts
  ui/e2e/instances/list/index.spec.ts
  ui/e2e/notificationmenu/index.spec.ts
  ui/e2e/services/details.spec.ts
  ui/e2e/services/list.spec.ts
  ui/e2e/utils/files.ts
  ui/e2e/utils/workflow.ts
  ui/src/api/files/schema.ts
  ui/src/api/files/utils.ts
  ui/src/api/services/query/services.ts
  ui/src/api/services/schema/services.ts
  ui/src/assets/locales/en/translation.json
  ui/src/assets/ts/workflow.d.ts
  ui/src/components/Breadcrumb/ExplorerBreadcrumb/BreadcrumbSegment.tsx
  ui/src/components/FilePicker/FileList.tsx
  ui/src/config/env/schema.ts
  ui/src/design/Editor/index.tsx
  ui/src/design/Editor/utils.ts
  ui/src/hooks/useTsWorkflowLibs.ts
  ui/src/pages/namespace/Explorer/Tree/FileRow/index.tsx
  ui/src/pages/namespace/Explorer/Tree/__tests__/utils.test.ts
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Gateway/Consumer.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Gateway/Route.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Service/index.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Workflow/index.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Workflow/templates.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/Rename.tsx
  ui/src/pages/namespace/Explorer/Tree/utils.ts
  ui/src/pages/namespace/Explorer/Workflow/Edit/CodeEditor.tsx
  ui/src/pages/namespace/Explorer/Workflow/Edit/WorkflowEditor.tsx
  ui/src/pages/namespace/Explorer/Workflow/components/RunWorkflow.tsx
  ui/src/pages/namespace/Explorer/Workflow/index.tsx
Labels: ui, feature

#1696 [DIR-1538] Add e2e test for error details in instance logs
  ui/e2e/instances/details/logs.spec.ts
Labels: ui, testing
