Repository direktiv/direktiv, pull requests merged in 2024-06, with the labels that each got.

#1625 [DIR-1608] Display error message on errors when fetching logs
  ui/e2e/instances/details/errorHandling.spec.ts
  ui/e2e/instances/filter/index.spec.ts
  ui/e2e/monitoring/index.spec.ts
  ui/e2e/utils/files.ts
  ui/src/api/__tests__/apiFactory.test.ts
  ui/src/api/authenticate/index.ts
  ui/src/api/errorHandling.ts
  ui/src/api/useInfiniteQueryWithPermissions.ts
  ui/src/api/useMutationWithPermissions.ts
  ui/src/api/useQueryWithPermissions.ts
  ui/src/assets/locales/en/translation.json
  ui/src/components/ApiError/index.tsx
  ui/src/pages/namespace/Explorer/index.tsx
  ui/src/pages/namespace/Instances/Detail/Main/Logs/index.tsx
  ui/src/pages/namespace/Layout.tsx
  ui/src/pages/namespace/Monitoring/Logs/index.tsx
  ui/src/util/router/ErrorPage.tsx
Labels: ui

#1633 [DIR-1555] Clear cache when deleting file
  ui/e2e/explorer/index.spec.ts
  ui/src/api/files/mutate/deleteFile.ts
Labels: bug, ui

#1649 [DIR-1062] build open api docs
  openapi/src/openapi.yaml
Labels: backend

#1650 [DIR-1606] remove migration sql commands form the schema
  pkg/database/db_schema.sql
Labels: backend

#1651 [DIR-1641] Pass api-key to sidecar
  pkg/service/helper.go
Labels: backend, refactor

#1627 [DIR-1416] Add sidecar tests
  .github/workflows/build.yml
  tests/actions/action_workflow_bash_files.test.js
  tests/actions/action_workflow_bash_vars.test.js
  tests/actions/action_workflow_response.test.js
Labels: testing, backend

#1638 [DIR-1619] remove {{ namespace }} placeholder in toast message, when a namespace was deleted
  ui/src/assets/locales/en/translation.json
Labels: bug, ui

#1619 [DIR-1417] Remove v1 error response schema from ui
  ui/src/api/__tests__/apiFactory.test.ts
  ui/src/api/errorHandling.ts
Labels: ui

#1652 [DIR-1595] Adaptations in E2E tests for Instances Details
  ui/e2e/instances/details/diagram.spec.ts
  ui/e2e/instances/details/errorHandling.spec.ts
  ui/e2e/instances/details/header.spec.ts
  ui/e2e/instances/details/inputOutput.spec.ts
  ui/e2e/instances/details/logs.spec.ts
  ui/e2e/instances/utils/workflows.ts
Labels: ui, testing

#1654 [DIR-1643] Add a logout button to the onboarding page
  ui/src/assets/locales/en/translation.json
  ui/src/components/LogoutButton/EnterpriseLogout.tsx
  ui/src/components/LogoutButton/OpenSourceLogout.tsx
  ui/src/components/LogoutButton/index.tsx
  ui/src/components/LogoutButton/types.ts
  ui/src/components/UserMenu/LogoutButton/EnterpriseLogout.tsx
  ui/src/components/UserMenu/LogoutButton/OpenSourceLogout.tsx
  ui/src/components/UserMenu/LogoutButton/index..tsx
  ui/src/components/UserMenu/index.tsx
  ui/src/hooks/useApiKeyHandling.ts
  ui/src/pages/OnboardingPage/index.tsx
Labels: improvement, ui

#1660 Rename gateway2 package to gateway
  .golangci.yaml
  cmd/direktiv/main.go
  pkg/api/api.go
  pkg/cmd/main.go
  pkg/core/app.go
  pkg/core/gateway.go
  pkg/gateway/context.go
  pkg/gateway/fetch_secret.go
  pkg/gateway/fetch_secret_test.go
  pkg/gateway/gateway.go
  pkg/gateway/helper.go
  pkg/gateway/plugins.go
  pkg/gateway/plugins/auth/basic-auth.go
  pkg/gateway/plugins/auth/github-event.go
  pkg/gateway/plugins/auth/gitlab-event.go
  pkg/gateway/plugins/auth/key-auth.go
  pkg/gateway/plugins/auth/slack-event.go
  pkg/gateway/plugins/inbound/acl-plugin.go
  pkg/gateway/plugins/inbound/header_manipulation.go
  pkg/gateway/plugins/inbound/js-inbound.go
  pkg/gateway/plugins/inbound/request-convert.go
  pkg/gateway/plugins/outbound/js_outbound.go
  pkg/gateway/plugins/target/debug_target.go
  pkg/gateway/plugins/target/instant-response.go
  pkg/gateway/plugins/target/request.go
  pkg/gateway/plugins/target/target-ns-file.go
  pkg/gateway/plugins/target/target-ns-var.go
  pkg/gateway/plugins/target/target-workflow-var.go
  pkg/gateway/plugins/target/target-workflow.go
  pkg/gateway/router.go
  pkg/gateway/router_test.go
  pkg/helpers/render.go
  pkg/mirror/parser.go
  pkg/model/resources.go
  tests/gateway/endpoints_crud.test.js
  tests/gateway2/acl_inbound.test.js
  tests/gateway2/basic.test.js
  tests/gateway2/basic_auth.test.js
  tests/gateway2/fetch_secret.test.js
  tests/gateway2/gitlab2_auth.test.js
  tests/gateway2/key_auth.test.js
Labels: refactor

#1661 House Keeping: fix docker files for multi-platform images
  .github/workflows/build.yml
  Dockerfile
  ui/Dockerfile
Labels: bug, backend

#1646 [DIR-1621] change events ordering
  pkg/api/events.go
  pkg/datastore/datastoresql/eventstore_history.go
  pkg/datastore/datastoresql/eventstore_history_test.go
  pkg/datastore/eventsstore.go
  ui/src/api/events/query/stream.ts
Labels: ui, backend

#1662 House Keeping: fix todos
  pkg/api/api.go
  pkg/api/filesystem.go
  pkg/api/namespaces.go
  pkg/cmd/main.go
  pkg/core/gateway.go
  pkg/core/service.go
  pkg/database/db_schema.sql
  pkg/filestore/filestore.go
  pkg/flow/server.go
  pkg/gateway/gateway.go
  pkg/gateway/plugins/inbound/request-convert.go
  pkg/gateway/plugins/target/target-workflow.go
  pkg/helpers/render.go
  pkg/pubsub/pubsub.go
  pkg/pubsub/pubsub_pg.go
  pkg/pubsub/sql/pubsub_core_pg.go
  pkg/service/manager.go
  tests/gateway/endpoints_crud.test.js
  tests/gateway/target_file.test.js
  tests/gateway/target_flow.test.js
  tests/part1/registry/multiple_namespaces.test.js
Labels: backend

#1664 House Keeping: remove global chanel in pubsub
  pkg/pubsub/pubsub.go
  pkg/pubsub/pubsub_pg.go
  pkg/pubsub/sql/pubsub_core_pg.go
Labels: backend, refactor

#1665 House Keeping: refactor pubsub
  pkg/api/filesystem.go
  pkg/api/namespaces.go
  pkg/cmd/main.go
  pkg/flow/engine.go
  pkg/flow/instance_messages.go
  pkg/flow/server.go
  pkg/gateway/plugins/target/target-ns-file.go
  pkg/gateway/plugins/target/target-ns-var.go
  pkg/gateway/plugins/target/target-workflow-var.go
  pkg/gateway/plugins/target/target-workflow.go
  pkg/helpers/bus.go
  pkg/pubsub/pubsub.go
  pkg/pubsub/pubsub_pg.go
  pkg/pubsub/sql/pubsub_core_pg.go
Labels: bug, backend

#1648 [DIR-1637] Add namespace log helper
  pkg/service/manager.go
  pkg/tracing/namespace_log.go
Labels: backend, refactor

#1657 [DIR-1640] Prepare to remove grpc from sidecar
  cmd/sidecar/local-server.go
  cmd/sidecar/worker.go
  tests/services/files.test.js
Labels: backend, refactor

#1667 [DIR-1667] Remove some grpc usage
  cmd/sidecar/api_v2_clients.go
  cmd/sidecar/local-server.go
  cmd/sidecar/types.go
  cmd/sidecar/worker.go
  tests/actions/action_workflow_bash_vars.test.js
Labels: backend, refactor

#1669 [DIR-1669] remove grpc from the sidecar part3
  cmd/sidecar/api_v2_clients.go
  cmd/sidecar/local-server.go
  cmd/sidecar/worker.go
  pkg/api/plattformlogs.go
  pkg/flow/temporary.go
  pkg/tracing/context_builder.go
Labels: backend, refactor

#1672 House Keeping: remove unused grpc
  pkg/flow/grpc-flow.go
  pkg/flow/grpc-instance-variables.go
  pkg/flow/grpc-internal.go
  pkg/flow/grpc-namespace-variables.go
  pkg/flow/grpc-workflow-variables.go
  pkg/flow/grpc/internal.pb.go
  pkg/flow/grpc/internal.proto
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
  pkg/flow/grpc/variables.pb.go
  pkg/flow/grpc/variables.proto
Labels: backend, refactor

#1673 [DIR-1673] Remove grpc
  pkg/flow/actionResults_test.go
  pkg/flow/engine.go
  pkg/flow/grpc-instance-variables.go
  pkg/flow/grpc-internal.go
  pkg/flow/grpc-namespace-variables.go
  pkg/flow/grpc/internal.pb.go
  pkg/flow/grpc/internal.proto
  pkg/flow/grpc/protocol.pb.go
  pkg/flow/grpc/protocol.proto
  pkg/flow/grpc/protocol_grpc.pb.go
  pkg/flow/scheduling.go
  pkg/flow/server.go
  pkg/flow/temporary.go
Labels: backend, refactor

#1671 [DIR-1573] Updated CLI
  cmd/exec/cli/events.go
  cmd/exec/cli/filesystem.go
  cmd/exec/cli/profile.go
  cmd/exec/cli/root.go
  cmd/exec/cli/uploader.go
  cmd/exec/cli/utils.go
  cmd/exec/cmd/config.go
  cmd/exec/cmd/config/conf.go
  cmd/exec/cmd/config/config-manager.go
  cmd/exec/cmd/config/project-conf-init.go
  cmd/exec/cmd/events/events.go
  cmd/exec/cmd/instance.go
  cmd/exec/cmd/logs.go
  cmd/exec/cmd/logs/logs.go
  cmd/exec/cmd/root.go
  cmd/exec/cmd/utils.go
  cmd/exec/cmd/workflows/info.go
  cmd/exec/cmd/workflows/workflows.go
  cmd/exec/main.go
  go.mod
  go.sum
  pkg/api/filesystem.go
Labels: improvement, cli

#1675 House Keeping: clean grpc usages
  charts/direktiv/templates/functions/functions-secrets.yaml
  charts/direktiv/templates/functions/functions-service.yaml
  cmd/direktiv/flow.go
  pkg/flow/server.go
Labels: backend, refactor

#1685 House Keeping: remove grpc port config
  .github/workflows/build.yml
  charts/direktiv/templates/flow/flow-deployment.yaml
  charts/direktiv/templates/flow/flow-service-headless.yaml
  charts/direktiv/templates/flow/flow-service.yaml
  docker-compose.yaml
  pkg/core/app.go
  pkg/service/helper.go
Labels: backend, refactor

#1663 [DIR-1662] Fix syntax
  tests/actions/action_workflow_bash_files.test.js
Labels: testing, backend

#1686 [DIR-1693] Bug fix for e2e test
  ui/e2e/explorer/index.spec.ts
Labels: ui, testing

#1681 [DIR-1403] Select number of items in a table
  ui/e2e/events/history.spec.ts
  ui/src/assets/locales/en/translation.json
  ui/src/pages/namespace/Events/History/EventsList.tsx
  ui/src/pages/namespace/Events/History/components/SelectPageSize/index.tsx
  ui/src/util/store/events.ts
Labels: improvement, ui
