Repository direktiv/direktiv, pull requests merged in 2024-01, with the labels that each got.

#1198 [DIR-1090] remove Post Start Exec from services
  ui/public/locales/en/translation.json
  ui/src/api/services/schema/services.ts
  ui/src/pages/namespace/Explorer/Service/ServiceHelp.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Service/config.ts
  ui/src/pages/namespace/Services/List/Row/PostStartExecs.tsx
  ui/src/pages/namespace/Services/List/Row/index.tsx
Labels: ui

#1216 [DIR-1113] Add file close to attribute for special command
  cmd/cmd-exec/pkg/commands/commands_test.go
  cmd/cmd-exec/pkg/server/server.go
  cmd/cmd-exec/pkg/server/server_test.go
Labels: bug, backend

#1222 [DIR-1120] Remove revisions completely
  cmd/exec/cmd/instance.go
  pkg/flow/bytedata/data2.go
  pkg/flow/engine.go
  pkg/flow/grpc-files.go
  pkg/flow/grpc-mirror.go
  pkg/flow/grpc-namespace-variables.go
  pkg/flow/grpc-namespaces.go
  pkg/flow/grpc-nodes.go
  pkg/flow/grpc-refs.go
  pkg/flow/grpc-workflow.go
  pkg/flow/isolate.go
  pkg/flow/metrics.go
  pkg/flow/routing.go
  pkg/flow/secrets.go
  pkg/flow/temporary.go
  pkg/metrics/metrics.go
  pkg/metrics/types.go
  pkg/refactor/database/database.go
  pkg/refactor/database/db_schema.sql
  pkg/refactor/datastore/runtime_variables_test.go
  pkg/refactor/engine/telemetry.go
  pkg/refactor/filestore/file.go
  pkg/refactor/filestore/filestore.go
  pkg/refactor/filestore/filestoresql/file_query.go
  pkg/refactor/filestore/filestoresql/filestore.go
  pkg/refactor/filestore/filestoresql/revision_query.go
  pkg/refactor/filestore/filestoresql/root_query.go
  pkg/refactor/filestore/revision.go
  pkg/refactor/filestore/root_test.go
  pkg/refactor/instancestore/instance.go
  pkg/refactor/instancestore/instance_data_query_test.go
  pkg/refactor/instancestore/instance_test.go
  pkg/refactor/instancestore/instancestoresql/instancestoresql_test.go
  pkg/refactor/instancestore/instancestoresql/sql.go
  pkg/refactor/mirror/apply.go
  tests/filesystem/update_file.test.js
Labels: improvement, backend

#1226 [DIR-1127] Update Multipass Scripts
  scripts/build/docker/all/multipass/generate-init.sh
  scripts/build/docker/all/multipass/init-template.yaml
  scripts/build/docker/all/multipass/init.yaml
  scripts/build/docker/all/multipass/install.sh
Labels: devops

#1202 [DIR-1091][DIR-1125][DIR-1126] add e2e tests to services, show env vars on service details page
  ui/e2e/services/details.spec.ts
  ui/e2e/services/list.spec.ts
  ui/e2e/services/utils.ts
  ui/public/locales/en/translation.json
  ui/src/components/Breadcrumb/ServicesBreadcrumb.tsx
  ui/src/pages/namespace/Services/Detail/Header.tsx
  ui/src/pages/namespace/Services/Detail/Pods/index.tsx
  ui/src/pages/namespace/Services/List/Row/index.tsx
  ui/src/pages/namespace/Services/List/index.tsx
  ui/src/pages/namespace/Services/components/EnvVariables.tsx
Labels: ui, testing

#1229 [DIR-1137] Refactor to core pubsub
  pkg/refactor/pubsub/sql/pubsub_core_pg.go
  pkg/refactor/pubsub/sql/pubsub_pg.go
Labels: backend

#1230 [DIR-1138] refactor backend pubsub
  pkg/flow/server.go
  pkg/refactor/cmd/main.go
  pkg/refactor/pubsub/pubsub.go
  pkg/refactor/pubsub/pubsub_pg.go
  pkg/refactor/pubsub/sql/pubsub_core_pg.go
  pkg/refactor/pubsub/sql/pubsub_pg.go
Labels: backend

#1204 [DIR-1074] service editor
  ui/e2e/explorer/service/index.spec.ts
  ui/public/locales/en/translation.json
  ui/src/api/services/schema/services.ts
  ui/src/pages/namespace/Explorer/Service/ServiceEditor.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/Form/Envs/EnvItemForm.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/Form/Envs/index.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/Form/index.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/index.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/schema.ts
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/utils.ts
  ui/src/pages/namespace/Explorer/Service/ServiceHelp.tsx
  ui/src/pages/namespace/Explorer/Service/index.tsx
  ui/src/pages/namespace/Explorer/Tree/Header.tsx
  ui/src/pages/namespace/Explorer/Tree/NewFile.tsx
  ui/src/pages/namespace/Explorer/Tree/NoResult.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Service/config.ts
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Service/index.tsx
Labels: ui

#1231 [DIR-1140] Fix field file.updated_at when updating a file content.
  pkg/refactor/filestore/file_test.go
  pkg/refactor/filestore/filestoresql/file_query.go
  pkg/refactor/filestore/filestoresql/root_query.go
  pkg/refactor/filestore/revision.go
  pkg/refactor/filestore/root_test.go
Labels: bug, backend

#1236 [DIR-1148] move-configure-workflow-func-to-new-main
  .golangci.yaml
  cmd/cmd-exec/pkg/commands/commands_test.go
  cmd/cmd-exec/pkg/server/logging_test.go
  cmd/cmd-exec/pkg/server/server_test.go
  pkg/flow/grpc-nodes.go
  pkg/flow/grpc-workflow.go
  pkg/flow/server.go
  pkg/refactor/cmd/main.go
  pkg/refactor/pubsub/pubsub.go
  tests/events/workflow_events_and.test.js
  tests/events/workflow_events_or.test.js
  ui/frontend/main.go
  ui/frontend/server/config.go
  ui/frontend/server/error.go
  ui/frontend/server/route-manager.go
  ui/frontend/server/route.go
  ui/frontend/server/server.go
Labels: backend, refactor

#1237 [DIR-1150] refactor-remove-isempty-from-filestore
  pkg/flow/grpc-namespaces.go
  pkg/flow/grpc-nodes.go
  pkg/refactor/filestore/filestore.go
  pkg/refactor/filestore/filestoresql/root_query.go
  pkg/refactor/filestore/root_test.go
  tests/mirror/mirror.test.js
Labels: backend, refactor

#1235 [DIR-1141] reenable the updated at in the code editor
  pkg/flow/grpc-workflow.go
  ui/e2e/errorPage.spec.ts
  ui/e2e/explorer/workflow/codeEditor.spec.ts
  ui/e2e/notificationmenu/index.spec.ts
  ui/public/locales/en/translation.json
  ui/src/pages/namespace/Explorer/Workflow/Edit/CodeEditor.tsx
  ui/src/pages/namespace/Explorer/Workflow/Edit/WorkflowEditor.tsx
  ui/src/util/router/ErrorPage.tsx
Labels: improvement, ui

#1238 [DIR-1152] remove-root-dir-entries-from-filestore
  pkg/flow/grpc-mirror.go
  pkg/flow/grpc-namespaces.go
  pkg/refactor/database/db_schema.sql
  pkg/refactor/datastore/runtime_variables_test.go
  pkg/refactor/filestore/file_test.go
  pkg/refactor/filestore/filestore.go
  pkg/refactor/filestore/filestoresql/file_query.go
  pkg/refactor/filestore/filestoresql/root_query.go
  pkg/refactor/filestore/root_test.go
  pkg/refactor/gateway/gateway_test.go
  pkg/refactor/mirror/mirror_test.go
  pkg/refactor/mirror/parser.go
  pkg/refactor/mirror/parser_test.go
Labels: backend, refactor

#1239 [DIR-1149] Moved Helm Charts
  .github/workflows/charts.yml
  Makefile
  charts/direktiv/.helmignore
  charts/direktiv/Chart.lock
  charts/direktiv/Chart.yaml
  charts/direktiv/README.md
  charts/direktiv/README.md.gotmpl
  charts/direktiv/charts/ingress-nginx-4.4.0.tgz
  charts/direktiv/charts/prometheus-15.18.0.tgz
  charts/direktiv/templates/NOTES.txt
  charts/direktiv/templates/_helpers.tpl
  charts/direktiv/templates/eventing.yaml
  charts/direktiv/templates/flow/flow-deployment.yaml
  charts/direktiv/templates/flow/flow-role-bind.yaml
  charts/direktiv/templates/flow/flow-role.yaml
  charts/direktiv/templates/flow/flow-sa.yaml
  charts/direktiv/templates/flow/flow-secrets.yaml
  charts/direktiv/templates/flow/flow-service-headless.yaml
  charts/direktiv/templates/flow/flow-service.yaml
  charts/direktiv/templates/fn-namespace.yaml
  charts/direktiv/templates/frontend/frontend-config.yaml
  charts/direktiv/templates/frontend/frontend-deployment.yaml
  charts/direktiv/templates/frontend/frontend-service.yaml
  charts/direktiv/templates/functions/functions-cm-config.yaml
  charts/direktiv/templates/functions/functions-role-cluster.yaml
  charts/direktiv/templates/functions/functions-role-ns.yaml
  charts/direktiv/templates/functions/functions-rolebind-cluster.yaml
  charts/direktiv/templates/functions/functions-rolebind-ns.yaml
  charts/direktiv/templates/functions/functions-sa-pod.yaml
  charts/direktiv/templates/functions/functions-sa.yaml
  charts/direktiv/templates/functions/functions-secrets.yaml
  charts/direktiv/templates/functions/functions-service.yaml
  charts/direktiv/templates/ingress-secret.yaml
  charts/direktiv/templates/ingress.yaml
  charts/direktiv/templates/telemetry/otel-agent-cm-config.yaml
  charts/direktiv/templates/telemetry/otel-agent-cm-config_ns.yaml
  charts/direktiv/templates/telemetry/otel-agent-cm-sidecar.yaml
  charts/direktiv/values.yaml
  scripts/build/docker/all/multipass/install.sh
  scripts/installer.sh
Labels: devops
