Repository direktiv/direktiv, pull requests merged in 2025-01, with the labels that each got.

#1741 [DIR-1896] Add OpenAPI basic file
  go.mod
  go.sum
  make_cluster.mk
  make_tests.mk
  pkg/core/gateway.go
  pkg/filestore/file.go
  pkg/gateway/gateway.go
  pkg/gateway/helper.go
  pkg/gateway/router.go
  pkg/helpers/render.go
  pkg/mirror/apply.go
  pkg/mirror/parser.go
  pkg/model/resources.go
  tests/gateway2/gateway_basic.test.js
  ui/src/api/files/schema.ts
Labels: feature, backend

#1742 [DIR-1496] - UI support for system namespace
  ui/src/assets/locales/en/translation.json
  ui/src/components/NamespaceEdit/index.tsx
  ui/src/components/NamespaceSelectorList/index.tsx
Labels: ui

#1739 [DIR-1897] Made pagination always visible and show page number 1 for an empty list
  ui/e2e/events/history.spec.ts
  ui/src/components/Pagination/index.tsx
  ui/src/components/PaginationProvider/index.tsx
  ui/src/pages/namespace/Events/History/EventsList.tsx
  ui/src/pages/namespace/Events/Listeners/index.tsx
  ui/src/pages/namespace/Explorer/Workflow/Settings/Variables/index.tsx
  ui/src/pages/namespace/Instances/List/index.tsx
  ui/src/pages/namespace/Mirror/Detail/index.tsx
  ui/src/pages/namespace/Settings/Registries/index.tsx
  ui/src/pages/namespace/Settings/Secrets/index.tsx
  ui/src/pages/namespace/Settings/Variables/index.tsx
Labels: improvement, ui

#1749 [HK] fix linter issues and minor bugs
  .github/workflows/build.yml
  .golangci.yaml
  cmd/cli/filesystem.go
  cmd/cli/flow.go
  pkg/api/middlewares.go
  pkg/cmdserver/pkg/server/server.go
  pkg/filestore/filestoresql/root_query.go
  pkg/flow/instance_messages.go
  pkg/flow/memory.go
  pkg/flow/scheduling.go
  pkg/flow/states/action.go
  pkg/flow/states/foreach.go
  pkg/flow/states/parallel.go
  pkg/flow/states/validate.go
  pkg/model/common-structures.go
  pkg/model/start-event.go
  pkg/model/start-events-and.go
  pkg/model/start-events-xor.go
  pkg/model/state-generate-event.go
  pkg/model/state-parallel.go
  pkg/model/state-switch.go
  pkg/utils/encrypt.go
Labels: refactor

#1746 [Dir-1913] Add independent pagesize setting to other tables: Instances
  ui/e2e/instances/filter/index.spec.ts
  ui/e2e/instances/list/index.spec.ts
  ui/e2e/instances/utils/workflows.ts
  ui/src/components/SelectPageSize/index.tsx
  ui/src/pages/namespace/Events/History/EventsList.tsx
  ui/src/pages/namespace/Events/Listeners/index.tsx
  ui/src/pages/namespace/Instances/List/index.tsx
  ui/src/util/store/pagesize.ts
Labels: improvement, ui

#1752 Fix e2e test
  ui/e2e/instances/list/index.spec.ts
Labels: bug, ui

#1745 [DIR-1520] - Add omitEmptyFields functionality for Service Editor
  ui/e2e/explorer/service/index.spec.ts
  ui/e2e/explorer/service/utils.ts
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/index.tsx
  ui/src/pages/namespace/Explorer/Service/ServiceEditor/utils.ts
Labels: ui

#1748 [DIR-1901] - Add info tab to gateview view
  ui/e2e/gateway/info/index.spec.ts
  ui/src/api/gateway/index.ts
  ui/src/api/gateway/query/getInfo.ts
  ui/src/api/gateway/schema.ts
  ui/src/assets/locales/en/translation.json
  ui/src/components/Breadcrumb/Gateway/GatewayInfo.tsx
  ui/src/components/Breadcrumb/Gateway/Routes.tsx
  ui/src/components/Breadcrumb/Gateway/index.tsx
  ui/src/pages/namespace/Gateway/Info/index.tsx
  ui/src/pages/namespace/Gateway/index.tsx
  ui/src/util/router/pages.tsx
Labels: ui, gateway

#1753 [DIR-1507] only quit silently on 404 errors in e2e test
  ui/e2e/gateway/routes/utils.ts
Labels: ui, testing

#1754 [DIR-1739] Fix pagination for events
  ui/src/components/Pagination/__tests__/describePagination.test.ts
  ui/src/components/Pagination/describePagination.ts
  ui/src/components/Pagination/index.tsx
  ui/src/components/Pagination/utils.ts
  ui/src/components/PaginationProvider/index.tsx
  ui/src/pages/namespace/Events/History/EventsList.tsx
  ui/src/pages/namespace/Events/Listeners/index.tsx
  ui/src/pages/namespace/Explorer/Workflow/Settings/Variables/index.tsx
  ui/src/pages/namespace/Instances/List/index.tsx
  ui/src/pages/namespace/Mirror/Detail/index.tsx
  ui/src/pages/namespace/Settings/Registries/index.tsx
  ui/src/pages/namespace/Settings/Secrets/index.tsx
  ui/src/pages/namespace/Settings/Variables/index.tsx
Labels: bug, ui

#1757 [DIR-1733] Space before first line causes workflow execution error
  ui/src/assets/locales/en/translation.json
  ui/src/pages/namespace/Explorer/Workflow/components/RunWorkflow.tsx
  ui/src/pages/namespace/Explorer/Workflow/components/utils.ts
Labels: ui
