Repository direktiv/direktiv, pull requests merged in 2025-03, with the labels that each got.

#1786 [DIR-1926] - Merge gateway info and routes tab to one page
  ui/e2e/gateway/consumers/index.spec.ts
  ui/e2e/gateway/info/index.spec.ts
  ui/e2e/gateway/routes/details/index.spec.ts
  ui/e2e/gateway/routes/list/index.spec.ts
  ui/src/assets/locales/en/translation.json
  ui/src/components/Breadcrumb/Gateway/Routes.tsx
  ui/src/pages/namespace/Gateway/Info/GatewayInfo.tsx
  ui/src/pages/namespace/Gateway/Info/OpenAPISpec.tsx
  ui/src/pages/namespace/Gateway/Info/ResizablePanel.tsx
  ui/src/pages/namespace/Gateway/Info/index.tsx
  ui/src/pages/namespace/Gateway/Info/useResizeDrag.tsx
  ui/src/pages/namespace/Gateway/Routes/Table/Row.tsx
  ui/src/pages/namespace/Gateway/Routes/Table/index.tsx
  ui/src/pages/namespace/Gateway/Routes/components/Methods.tsx
  ui/src/pages/namespace/Gateway/Routes/index.tsx
  ui/src/pages/namespace/Gateway/index.tsx
  ui/src/util/store/panelSize.ts
Labels: ui, feature, gateway

#1788 [DIR-1973] fix runtime variables update on file path change
  pkg/api/filesystem.go
Labels: bug, backend

#1790 Changed font Rapidoc
  ui/src/design/RapiDoc/index.tsx
  ui/src/design/RapiDoc/styles/RapiDoc.css
Labels: ui

#1791 [DIR-1995] fix bug: namespace 'api', 'v2' or 'namespace' could break the backend logic
  tests/part2/namespaces/basic_create.test.js
Labels: bug, backend

#1776 [DIR-1950] Improve error handling in router
  ui/src/components/Router/index.tsx
  ui/src/pages/namespace/Gateway/Routes/Detail/index.tsx
  ui/src/routes/*.tsx
  ui/src/util/router/NotFoundPage.tsx
Labels: bug, ui

#1792 Makes garbage collection configurable.
  pkg/core/app.go
  pkg/flow/grpc-flow.go
  pkg/flow/server.go
  pkg/instancestore/instancestoresql/sql.go
  pkg/mirror/manager.go
Labels: improvement, configuration, backend

#1794 [DIR-1996] endpoint namespaces is public
  pkg/api/namespaces.go
Labels: bug, backend

#1795 [DIR-1974] Fix logging (UI)
  ui/src/api/instances/schema.ts
  ui/src/api/logs/index.ts
  ui/src/api/logs/query/logs.ts
  ui/src/api/logs/schema.ts
  ui/src/components/Logs/useLogVirtualizer.ts
  ui/src/components/Logs/utils.ts
  ui/src/pages/namespace/Gateway/Routes/Detail/Logs/Entry.tsx
  ui/src/pages/namespace/Instances/Detail/Main/Logs/Entry.tsx
  ui/src/pages/namespace/Mirror/Detail/Sync/Logs/Entry.tsx
  ui/src/pages/namespace/Monitoring/Logs/Entry.tsx
Labels: bug, ui
