Repository direktiv/direktiv, pull requests merged in 2025-02, with the labels that each got.

#1762 [DIR-1937] Unused Files and Configuration for Opentelemetry
  charts/direktiv/templates/_helpers.tpl
  charts/direktiv/templates/flow/flow-deployment.yaml
  charts/direktiv/templates/functions/functions-cm-config.yaml
  charts/direktiv/templates/telemetry/otel-agent-cm-config.yaml
  charts/direktiv/templates/telemetry/otel-agent-cm-config_ns.yaml
  charts/direktiv/templates/telemetry/otel-agent-cm-sidecar.yaml
  charts/direktiv/values.yaml
Labels: backend, refactor

#1763 [DIR-1938] Remove opensearch feature flag
  charts/direktiv/Chart.lock
  charts/direktiv/Chart.yaml
  charts/direktiv/charts/fluent-bit-0.46.7.tgz
  charts/direktiv/charts/fluent-bit-0.48.5.tgz
  charts/direktiv/charts/opensearch-2.27.1.tgz
  charts/direktiv/templates/flow/flow-deployment.yaml
  charts/direktiv/values.yaml
  pkg/core/app.go
  pkg/flow/server.go
Labels: backend, refactor

#1767 [DIR-1941] Restore gateway tabs
  ui/e2e/gateway/consumers/index.spec.ts
  ui/e2e/gateway/routes/details/index.spec.ts
  ui/e2e/gateway/routes/list/index.spec.ts
  ui/src/components/Breadcrumb/Gateway/Routes.tsx
  ui/src/components/Breadcrumb/Gateway/index.tsx
  ui/src/components/Breadcrumb/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/index.tsx
  ui/src/pages/namespace/Gateway/Routes/Detail/Header.tsx
  ui/src/pages/namespace/Gateway/Routes/Detail/index.tsx
  ui/src/pages/namespace/Gateway/Routes/Table/Row.tsx
  ui/src/pages/namespace/Gateway/index.tsx
  ui/src/routeTree.gen.ts
  ui/src/routes/n/$namespace/gateway/index.tsx
  ui/src/routes/n/$namespace/gateway/route.tsx
  ui/src/routes/n/$namespace/gateway/routes/$.tsx
Labels: bug, ui

#1770 [DIR-1940] Added timeout with tests
  openapi/src/objects.yaml
  openapi/src/paths/gateway.yaml
  openapi/src/paths/paths.yaml
  pkg/gateway/router.go
  tests/gateway2/timeout.test.js
Labels: bug, backend

#1764 [DIR-1934] fix flaky instances tests
  ui/e2e/instances/details/diagram.spec.ts
  ui/e2e/instances/details/header.spec.ts
  ui/e2e/instances/details/inputOutput.spec.ts
  ui/e2e/instances/details/logs.spec.ts
  ui/e2e/instances/list/index.spec.ts
  ui/e2e/instances/utils/workflows.ts
  ui/src/api/instances/schema.ts
  ui/src/components/SelectPageSize/index.tsx
Labels: ui, testing

#1772 [DIR-1942] Integrate helm-chart dependencies to flow
  .github/workflows/charts.yml
  charts/direktiv/Chart.lock
  charts/direktiv/Chart.yaml
  charts/direktiv/charts/victoria-logs-single-0.8.16.tgz
  charts/direktiv/templates/flow/flow-deployment.yaml
  charts/direktiv/templates/flow/flow-secrets-fluentbit.yaml
  charts/direktiv/values.yaml
  pkg/core/app.go
Labels: charts

#1777 [DIR-1948] Fix sync param for displaying sync logs
  ui/e2e/mirror.spec.ts
  ui/src/pages/namespace/Mirror/Detail/Sync/SyncDetail.tsx
  ui/src/pages/namespace/Mirror/Detail/Sync/index.tsx
Labels: bug, ui

#1783 [DIR-1956] Added server variable to openapi docs
  make_tests.mk
  openapi/src/paths/gateway.yaml
  pkg/gateway/gateway.go
Labels: improvement, backend

#1781 [DIR-1923] PR review
  ui/e2e/explorer/route/index.spec.ts
  ui/e2e/explorer/route/utils.ts
  ui/e2e/gateway/routes/utils.ts
  ui/src/api/gateway/query/getRoutes.ts
  ui/src/api/gateway/schema.ts
  ui/src/assets/locales/en/translation.json
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/ErrorMessage.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/methodCheckbox.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/utils.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/__tests__/utils.test.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/index.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/utils.ts
  ui/src/pages/namespace/Gateway/Routes/Detail/Header.tsx
  ui/src/pages/namespace/Gateway/Routes/Detail/index.tsx
  ui/src/pages/namespace/Gateway/Routes/Table/Row.tsx
  ui/src/pages/namespace/Gateway/Routes/Table/index.tsx
  ui/src/pages/namespace/Gateway/Routes/components/Anonymous.tsx
  ui/src/pages/namespace/Gateway/Routes/components/Methods.tsx
  ui/src/pages/namespace/Gateway/Routes/components/Plugins.tsx
  ui/src/pages/namespace/Gateway/Routes/utils.ts
Labels: ui, refactor

#1775 [DIR-1923] - Update Gateway and Endpoint editor for new Endpoint/v2 Structure
  ui/e2e/explorer/route/index.spec.ts
  ui/e2e/explorer/route/utils.ts
  ui/e2e/gateway/routes/details/index.spec.ts
  ui/e2e/gateway/routes/list/index.spec.ts
  ui/e2e/gateway/routes/utils.ts
  ui/src/api/gateway/schema.ts
  ui/src/components/Breadcrumb/Gateway/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/ErrorMessage.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/methodCheckbox.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Auth/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Inbound/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Outbound/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/utils.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/__tests__/utils.test.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/index.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/utils.ts
  ui/src/pages/namespace/Gateway/Routes/Detail/Header.tsx
  ui/src/pages/namespace/Gateway/Routes/Detail/index.tsx
  ui/src/pages/namespace/Gateway/Routes/Table/Row.tsx
  ui/src/pages/namespace/Gateway/Routes/Table/index.tsx
  ui/src/pages/namespace/Gateway/Routes/components/Anonymous.tsx
  ui/src/pages/namespace/Gateway/Routes/components/Methods.tsx
  ui/src/pages/namespace/Gateway/Routes/components/Plugins.tsx
  ui/src/pages/namespace/Gateway/Routes/index.tsx
  ui/src/pages/namespace/Gateway/Routes/utils.ts
Labels: improvement, ui, feature, gateway

#1773 [DIR-1960] - OpenAPI UI
  ui/e2e/explorer/consumer/index.spec.ts
  ui/e2e/explorer/index.spec.ts
  ui/e2e/explorer/route/index.spec.ts
  ui/e2e/explorer/route/utils.ts
  ui/e2e/explorer/service/index.spec.ts
  ui/e2e/explorer/workflow/run.spec.ts
  ui/e2e/gateway/info/index.spec.ts
  ui/e2e/gateway/info/utils.ts
  ui/e2e/gateway/routes/details/index.spec.ts
  ui/e2e/gateway/routes/list/index.spec.ts
  ui/e2e/gateway/routes/utils.ts
  ui/src/api/files/schema.ts
  ui/src/api/files/utils.ts
  ui/src/api/gateway/index.ts
  ui/src/api/gateway/query/getInfo.ts
  ui/src/api/gateway/schema.ts
  ui/src/assets/locales/en/translation.json
  ui/src/components/Breadcrumb/Gateway/GatewayInfo.tsx
  ui/src/components/Breadcrumb/Gateway/index.tsx
  ui/src/components/Navigation/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/ErrorMessage.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/methodCheckbox.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Auth/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Inbound/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Outbound/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/plugins/Target/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/Form/utils.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/__tests__/utils.test.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/index.tsx
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/schema/index.ts
  ui/src/pages/namespace/Explorer/Endpoint/EndpointEditor/utils.ts
  ui/src/pages/namespace/Explorer/OpenapiSpecification/OpenApiSpecificationEditor/index.tsx
  ui/src/pages/namespace/Explorer/OpenapiSpecification/OpenApiSpecificationEditor/schema.ts
  ui/src/pages/namespace/Explorer/OpenapiSpecification/index.tsx
  ui/src/pages/namespace/Explorer/Tree/NewFile.tsx
  ui/src/pages/namespace/Explorer/Tree/components/NewFileButton.tsx
  ui/src/pages/namespace/Explorer/Tree/components/modals/CreateNew/Gateway/OpenapiSpecification.tsx
  ui/src/pages/namespace/Explorer/Workflow/Edit/CodeEditor.tsx
  ui/src/pages/namespace/Gateway/Info/index.tsx
  ui/src/pages/namespace/Gateway/Routes/Detail/Header.tsx
  ui/src/pages/namespace/Gateway/Routes/Detail/index.tsx
  ui/src/pages/namespace/Gateway/Routes/Table/Row.tsx
  ui/src/pages/namespace/Gateway/Routes/Table/index.tsx
  ui/src/pages/namespace/Gateway/Routes/components/Anonymous.tsx
  ui/src/pages/namespace/Gateway/Routes/components/Methods.tsx
  ui/src/pages/namespace/Gateway/Routes/components/Plugins.tsx
  ui/src/pages/namespace/Gateway/Routes/index.tsx
  ui/src/pages/namespace/Gateway/Routes/utils.ts
  ui/src/pages/namespace/Gateway/index.tsx
  ui/src/routeTree.gen.ts
  ui/src/routes/n/$namespace/explorer/openapiSpecification.$.tsx
  ui/src/routes/n/$namespace/gateway/gatewayInfo.tsx
Labels: ui, feature

#1785 [DIR-1970] - Fix navigation active state bug
  ui/src/components/Navigation/index.tsx
  ui/src/routeTree.gen.ts
  ui/src/routes/n/$namespace/events/index.tsx
  ui/src/routes/n/$namespace/gateway/index.tsx
Labels: bug, ui

#1782 [DIR-1957] - Add gateway openapi document view section
  ui/e2e/errorPage.spec.ts
  ui/e2e/gateway/documentation/index.spec.ts
  ui/e2e/gateway/info/index.spec.ts
  ui/src/api/gateway/index.ts
  ui/src/api/gateway/query/getInfo.ts
  ui/src/assets/locales/en/translation.json
  ui/src/components/Breadcrumb/Gateway/Documentation.tsx
  ui/src/components/Breadcrumb/Gateway/index.tsx
  ui/src/design/RapiDoc/index.tsx
  ui/src/design/RapiDoc/styles/RapiDoc.css
  ui/src/pages/namespace/Gateway/Info/index.tsx
  ui/src/pages/namespace/Gateway/OpenapiDoc/index.tsx
  ui/src/pages/namespace/Gateway/index.tsx
  ui/src/routeTree.gen.ts
  ui/src/routes/n/$namespace/gateway/openapiDoc.tsx
  ui/vite.config.mts
Labels: improvement, feature, gateway
