Repository direktiv/direktiv, pull requests merged in 2025-07, with the labels that each got.

#1836 [TDI-52] Add side panel to edit blocks
  ui/src/assets/locales/en/translation.json
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/BlockDialogProvider.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/EditorPanelProvider.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/Headline.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/InlineBlockSidePanel.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/QueryProvider/index.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/Text.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/BlockDialogContent.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/ContextMenu.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/Delete.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/EditorPanelContent.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/Footer.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/Header.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/SelectType.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/index.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockList.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockWrapper.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/pageCompilerContext.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils/useCreateBlock.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/index.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageEditor/index.tsx
Labels: ui, feature

#1842 [TDI-57] Allow cards below other cards
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockList.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/__tests__/utils.test.ts
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils/index.ts
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils/useBlockTypes.tsx
Labels: ui, feature

#1849 [TDI-66] Make dialogs in page editor preview local
  ui/src/design/Dialog/index.stories.tsx
  ui/src/design/Dialog/index.tsx
  ui/src/design/DragAndDropEditor/DraggableElement/index.tsx
  ui/src/design/LocalDialog/container.tsx
  ui/src/design/LocalDialog/index.stories.tsx
  ui/src/design/LocalDialog/index.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/EditorPanelProvider.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/Dialog.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockWrapper.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/__tests__/utils.test.ts
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils/index.ts
Labels: ui, feature

#1847 [TDI-61] Admins can add blocks with dnd interaction
  ui/src/assets/locales/en/translation.json
  ui/src/design/DragAndDrop/Draggable.tsx
  ui/src/design/DragAndDrop/Dropzone.tsx
  ui/src/design/DragAndDrop/index.stories.tsx
  ui/src/design/DragAndDrop/index.tsx
  ui/src/design/DragAndDrop/schema.ts
  ui/src/design/DragAndDropEditor/Context.tsx/index.stories.tsx
  ui/src/design/DragAndDropEditor/Context.tsx/index.tsx
  ui/src/design/DragAndDropEditor/DraggableElement/index.tsx
  ui/src/design/DragAndDropEditor/DroppableSeparator/index.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/EditorPanelProvider.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/EditorPanel.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/EditorPanelContent.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/SelectType.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/index.tsx
  ui/src/pages/namespace/Explorer/Page/poc/DndContextProvider/index.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockList.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockWrapper.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/__tests__/utils.test.ts
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils/index.ts
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils/useCreateBlock.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/index.tsx
  ui/src/pages/namespace/Explorer/Page/poc/schema/blocks/index.ts
Labels: ui

#1848 [TDI-77] Introduce a single configuration layer for all page blocks
  ui/src/design/DragAndDrop/schema.ts
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/EditorPanelProvider.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/NoFormBlockSidePanel.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/Table/ActionForm.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/EditorPanel.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/FormWrapper.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/Header.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/index.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/index.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockWrapper.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/__tests__/utils/index.ts
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/__tests__/utils.test.ts
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/pageCompilerContext.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils/index.ts
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils/types.ts
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils/useBlockTypes.tsx
  ui/src/pages/namespace/Explorer/Page/poc/schema/blocks/card.ts
  ui/src/pages/namespace/Explorer/Page/poc/schema/blocks/columns.ts
  ui/src/pages/namespace/Explorer/Page/poc/schema/blocks/dialog.ts
  ui/src/pages/namespace/Explorer/Page/poc/schema/blocks/form.ts
  ui/src/pages/namespace/Explorer/Page/poc/schema/blocks/index.ts
  ui/src/pages/namespace/Explorer/Page/poc/schema/blocks/loop.ts
  ui/src/pages/namespace/Explorer/Page/poc/schema/blocks/queryProvider.ts
  ui/src/pages/namespace/Explorer/Page/poc/schema/blocks/table/index.ts
  ui/src/pages/namespace/Explorer/Page/poc/schema/blocks/utils.ts
  ui/src/pages/namespace/Explorer/Page/poc/schema/index.ts
Labels: ui

#1852 [TDI-90] Show dropzone after every block instead of before
  ui/src/design/DragAndDrop/Draggable.tsx
  ui/src/design/DragAndDrop/index.stories.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/EditorPanel.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockWrapper.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/__tests__/utils.test.ts
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils/index.ts
Labels: ui

#1853 [TDI-87] Limit enabled dropzones to dialog if dialog is open
  ui/src/design/DragAndDrop/Dropzone.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/EditorPanelProvider.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/EditorPanel.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/Dialog.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockWrapper.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/__tests__/utils.test.ts
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/utils/index.ts
Labels: ui

#1855 [TDI-80] overhaul page editor bottom toolbar
  ui/src/assets/locales/en/translation.json
  ui/src/design/DragAndDrop/Draggable.tsx
  ui/src/design/LocalDialog/container.tsx
  ui/src/design/LocalDialog/index.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/EditorPanelProvider.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/Delete.tsx
  ui/src/pages/namespace/Explorer/Page/poc/BlockEditor/components/EditorPanel.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/context/pageCompilerContext.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageEditor/EditorModeSwitcher.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageEditor/index.tsx
Labels: ui

#1858 [TDI-86] Update go-git to v6
  cmd/cli/uploader_helper.go
  go.mod
  go.sum
  pkg/mirror/parser.go
  pkg/mirror/source.go
Labels: backend, dependencies

#1859 [TDI-88] JSON response in command
  pkg/cmdserver/pkg/commands/commands.go
Labels: feature, backend

#1854 [TDI-91] update drag and drop to only show on hover
  ui/src/design/DragAndDrop/Draggable.tsx
  ui/src/design/DragAndDrop/Dropzone.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockList.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/Block/utils/BlockWrapper.tsx
  ui/src/pages/namespace/Explorer/Page/poc/PageCompiler/primitives/Variable/index.tsx
Labels: ui

#1850 [TDI-79] RFC: form primitives spec
  ui/src/pages/namespace/Explorer/Page/poc/schema/primitives/extendedKeyValue/array.ts
  ui/src/pages/namespace/Explorer/Page/poc/schema/primitives/extendedKeyValue/index.ts
  ui/src/pages/namespace/Explorer/Page/poc/schema/primitives/extendedKeyValue/object.ts
  ui/src/pages/namespace/Explorer/Page/poc/schema/primitives/keyValue.ts
  ui/src/pages/namespace/Explorer/Page/poc/schema/procedures/mutation.ts
  ui/src/pages/namespace/Explorer/Page/poc/schema/spec/index.md
Labels: ui
